// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"database/sql"
)

const insertAuditEntry = `-- name: InsertAuditEntry :one
INSERT INTO audit_log (id, project_id, actor, action, target_type, target_id, metadata, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, actor, "action", target_type, target_id, metadata, created_at
`

type InsertAuditEntryParams struct {
	ID         string         `json:"id"`
	ProjectID  sql.NullString `json:"project_id"`
	Actor      string         `json:"actor"`
	Action     string         `json:"action"`
	TargetType string         `json:"target_type"`
	TargetID   string         `json:"target_id"`
	Metadata   string         `json:"metadata"`
	CreatedAt  string         `json:"created_at"`
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, insertAuditEntry,
		arg.ID,
		arg.ProjectID,
		arg.Actor,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Actor,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditByProject = `-- name: ListAuditByProject :many
SELECT id, project_id, actor, "action", target_type, target_id, metadata, created_at FROM audit_log
WHERE project_id = ?
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListAuditByProjectParams struct {
	ProjectID sql.NullString `json:"project_id"`
	Limit     int64          `json:"limit"`
}

func (q *Queries) ListAuditByProject(ctx context.Context, arg ListAuditByProjectParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditByProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Actor,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentActivity = `-- name: ListRecentActivity :many
SELECT
    a.actor,
    a.action,
    a.target_type,
    a.target_id,
    a.metadata,
    a.created_at,
    p.key  AS project_key,
    p.name AS project_name
FROM audit_log a
LEFT JOIN projects p ON p.id = a.project_id
ORDER BY a.created_at DESC, a.id DESC
LIMIT ?
`

type ListRecentActivityRow struct {
	Actor       string         `json:"actor"`
	Action      string         `json:"action"`
	TargetType  string         `json:"target_type"`
	TargetID    string         `json:"target_id"`
	Metadata    string         `json:"metadata"`
	CreatedAt   string         `json:"created_at"`
	ProjectKey  sql.NullString `json:"project_key"`
	ProjectName sql.NullString `json:"project_name"`
}

// Instance-wide recent mutations for the dashboard feed, joined to the project
// they touched (project_id is nullable for instance-level events).
func (q *Queries) ListRecentActivity(ctx context.Context, limit int64) ([]ListRecentActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentActivity, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentActivityRow{}
	for rows.Next() {
		var i ListRecentActivityRow
		if err := rows.Scan(
			&i.Actor,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
			&i.ProjectKey,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
