// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cargo.sql

package db

import (
	"context"
)

const cargoVersionExists = `-- name: CargoVersionExists :one
SELECT COUNT(*) FROM cargo_versions v
JOIN cargo_crates c ON c.id = v.crate_id
WHERE c.repository_id = ? AND c.name_lower = ? AND v.version = ?
`

type CargoVersionExistsParams struct {
	RepositoryID string `json:"repository_id"`
	NameLower    string `json:"name_lower"`
	Version      string `json:"version"`
}

func (q *Queries) CargoVersionExists(ctx context.Context, arg CargoVersionExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, cargoVersionExists, arg.RepositoryID, arg.NameLower, arg.Version)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCargoVersion = `-- name: DeleteCargoVersion :execrows
DELETE FROM cargo_versions
WHERE crate_id = (SELECT id FROM cargo_crates WHERE repository_id = ? AND name_lower = ?)
  AND version = ?
`

type DeleteCargoVersionParams struct {
	RepositoryID string `json:"repository_id"`
	NameLower    string `json:"name_lower"`
	Version      string `json:"version"`
}

func (q *Queries) DeleteCargoVersion(ctx context.Context, arg DeleteCargoVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCargoVersion, arg.RepositoryID, arg.NameLower, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCargoVersion = `-- name: GetCargoVersion :one
SELECT v.crate_id, v.blob_digest, v.size, v.cksum, v.upstream_url
FROM cargo_versions v
JOIN cargo_crates c ON c.id = v.crate_id
WHERE c.repository_id = ? AND c.name_lower = ? AND v.version = ?
`

type GetCargoVersionParams struct {
	RepositoryID string `json:"repository_id"`
	NameLower    string `json:"name_lower"`
	Version      string `json:"version"`
}

type GetCargoVersionRow struct {
	CrateID     string `json:"crate_id"`
	BlobDigest  string `json:"blob_digest"`
	Size        int64  `json:"size"`
	Cksum       string `json:"cksum"`
	UpstreamUrl string `json:"upstream_url"`
}

// Resolve a crate version to its content for download (by lowercased name).
func (q *Queries) GetCargoVersion(ctx context.Context, arg GetCargoVersionParams) (GetCargoVersionRow, error) {
	row := q.db.QueryRowContext(ctx, getCargoVersion, arg.RepositoryID, arg.NameLower, arg.Version)
	var i GetCargoVersionRow
	err := row.Scan(
		&i.CrateID,
		&i.BlobDigest,
		&i.Size,
		&i.Cksum,
		&i.UpstreamUrl,
	)
	return i, err
}

const insertCargoVersion = `-- name: InsertCargoVersion :exec
INSERT INTO cargo_versions (id, crate_id, version, index_line, cksum, blob_digest, size, yanked, upstream_url, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (crate_id, version)
DO UPDATE SET
    index_line   = excluded.index_line,
    cksum        = excluded.cksum,
    size         = CASE WHEN excluded.blob_digest != '' THEN excluded.size ELSE cargo_versions.size END,
    yanked       = excluded.yanked,
    upstream_url = excluded.upstream_url,
    blob_digest  = CASE WHEN excluded.blob_digest != '' THEN excluded.blob_digest ELSE cargo_versions.blob_digest END
`

type InsertCargoVersionParams struct {
	ID          string `json:"id"`
	CrateID     string `json:"crate_id"`
	Version     string `json:"version"`
	IndexLine   string `json:"index_line"`
	Cksum       string `json:"cksum"`
	BlobDigest  string `json:"blob_digest"`
	Size        int64  `json:"size"`
	Yanked      int64  `json:"yanked"`
	UpstreamUrl string `json:"upstream_url"`
	CreatedAt   string `json:"created_at"`
}

// Record a crate version. On conflict (a proxy re-listing, or a download filling
// a cached row) update metadata and only overwrite the blob when a real digest is
// supplied, so a fresh index read never clears a cached blob.
func (q *Queries) InsertCargoVersion(ctx context.Context, arg InsertCargoVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertCargoVersion,
		arg.ID,
		arg.CrateID,
		arg.Version,
		arg.IndexLine,
		arg.Cksum,
		arg.BlobDigest,
		arg.Size,
		arg.Yanked,
		arg.UpstreamUrl,
		arg.CreatedAt,
	)
	return err
}

const listAllCargoCrates = `-- name: ListAllCargoCrates :many
SELECT
    p.key         AS project_key,
    p.name        AS project_name,
    r.key         AS repo_key,
    c.name        AS crate_name,
    COUNT(v.id)   AS version_count,
    CAST(COALESCE(SUM(v.size), 0) AS INTEGER) AS size_bytes,
    CAST(r.mode = 'proxy' AS INTEGER) AS is_proxy,
    c.updated_at  AS updated_at
FROM cargo_crates c
JOIN repositories r ON r.id = c.repository_id
JOIN projects p ON p.id = r.project_id
LEFT JOIN cargo_versions v ON v.crate_id = c.id
GROUP BY c.id
ORDER BY p.key ASC, r.key ASC, c.name_lower ASC
`

type ListAllCargoCratesRow struct {
	ProjectKey   string `json:"project_key"`
	ProjectName  string `json:"project_name"`
	RepoKey      string `json:"repo_key"`
	CrateName    string `json:"crate_name"`
	VersionCount int64  `json:"version_count"`
	SizeBytes    int64  `json:"size_bytes"`
	IsProxy      int64  `json:"is_proxy"`
	UpdatedAt    string `json:"updated_at"`
}

// Every Cargo crate across all repositories, with version count, total cached
// size, and a proxy flag, for the browser's project-grouped index.
func (q *Queries) ListAllCargoCrates(ctx context.Context) ([]ListAllCargoCratesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllCargoCrates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllCargoCratesRow{}
	for rows.Next() {
		var i ListAllCargoCratesRow
		if err := rows.Scan(
			&i.ProjectKey,
			&i.ProjectName,
			&i.RepoKey,
			&i.CrateName,
			&i.VersionCount,
			&i.SizeBytes,
			&i.IsProxy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCargoBlobDigests = `-- name: ListCargoBlobDigests :many
SELECT DISTINCT blob_digest FROM cargo_versions WHERE blob_digest != ''
`

// Distinct blob digests every cached/published .crate references, for GC.
func (q *Queries) ListCargoBlobDigests(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCargoBlobDigests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blob_digest string
		if err := rows.Scan(&blob_digest); err != nil {
			return nil, err
		}
		items = append(items, blob_digest)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCargoIndexLines = `-- name: ListCargoIndexLines :many
SELECT v.index_line, v.version, v.yanked
FROM cargo_versions v
JOIN cargo_crates c ON c.id = v.crate_id
WHERE c.repository_id = ? AND c.name_lower = ?
ORDER BY v.created_at ASC
`

type ListCargoIndexLinesParams struct {
	RepositoryID string `json:"repository_id"`
	NameLower    string `json:"name_lower"`
}

type ListCargoIndexLinesRow struct {
	IndexLine string `json:"index_line"`
	Version   string `json:"version"`
	Yanked    int64  `json:"yanked"`
}

// Every version's index line for a crate (by lowercased name), newest last, for
// the sparse index file. yanked is returned so the served line reflects the
// current flag without rewriting the stored line on every yank/unyank.
func (q *Queries) ListCargoIndexLines(ctx context.Context, arg ListCargoIndexLinesParams) ([]ListCargoIndexLinesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCargoIndexLines, arg.RepositoryID, arg.NameLower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCargoIndexLinesRow{}
	for rows.Next() {
		var i ListCargoIndexLinesRow
		if err := rows.Scan(&i.IndexLine, &i.Version, &i.Yanked); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCargoVersionsForCrate = `-- name: ListCargoVersionsForCrate :many
SELECT v.version, v.size, v.yanked, v.cksum
FROM cargo_versions v
JOIN cargo_crates c ON c.id = v.crate_id
WHERE c.repository_id = ? AND c.name_lower = ?
ORDER BY v.created_at DESC
`

type ListCargoVersionsForCrateParams struct {
	RepositoryID string `json:"repository_id"`
	NameLower    string `json:"name_lower"`
}

type ListCargoVersionsForCrateRow struct {
	Version string `json:"version"`
	Size    int64  `json:"size"`
	Yanked  int64  `json:"yanked"`
	Cksum   string `json:"cksum"`
}

// Every version of a crate for its detail page.
func (q *Queries) ListCargoVersionsForCrate(ctx context.Context, arg ListCargoVersionsForCrateParams) ([]ListCargoVersionsForCrateRow, error) {
	rows, err := q.db.QueryContext(ctx, listCargoVersionsForCrate, arg.RepositoryID, arg.NameLower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCargoVersionsForCrateRow{}
	for rows.Next() {
		var i ListCargoVersionsForCrateRow
		if err := rows.Scan(
			&i.Version,
			&i.Size,
			&i.Yanked,
			&i.Cksum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCargoVersionsForRetention = `-- name: ListCargoVersionsForRetention :many
SELECT c.name_lower AS name_lower, v.version AS version, v.created_at AS created_at
FROM cargo_versions v
JOIN cargo_crates c ON c.id = v.crate_id
WHERE c.repository_id = ?
ORDER BY c.name_lower ASC, v.created_at DESC
`

type ListCargoVersionsForRetentionRow struct {
	NameLower string `json:"name_lower"`
	Version   string `json:"version"`
	CreatedAt string `json:"created_at"`
}

// Every version in a repository, grouped by crate and newest first, for pruning.
func (q *Queries) ListCargoVersionsForRetention(ctx context.Context, repositoryID string) ([]ListCargoVersionsForRetentionRow, error) {
	rows, err := q.db.QueryContext(ctx, listCargoVersionsForRetention, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCargoVersionsForRetentionRow{}
	for rows.Next() {
		var i ListCargoVersionsForRetentionRow
		if err := rows.Scan(&i.NameLower, &i.Version, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCargoVersionBlob = `-- name: SetCargoVersionBlob :exec
UPDATE cargo_versions SET blob_digest = ?, size = ?
WHERE crate_id = (SELECT id FROM cargo_crates WHERE repository_id = ? AND name_lower = ?)
  AND version = ?
`

type SetCargoVersionBlobParams struct {
	BlobDigest   string `json:"blob_digest"`
	Size         int64  `json:"size"`
	RepositoryID string `json:"repository_id"`
	NameLower    string `json:"name_lower"`
	Version      string `json:"version"`
}

// Fill a proxied version's cached blob after downloading the .crate.
func (q *Queries) SetCargoVersionBlob(ctx context.Context, arg SetCargoVersionBlobParams) error {
	_, err := q.db.ExecContext(ctx, setCargoVersionBlob,
		arg.BlobDigest,
		arg.Size,
		arg.RepositoryID,
		arg.NameLower,
		arg.Version,
	)
	return err
}

const setCargoYanked = `-- name: SetCargoYanked :execrows
UPDATE cargo_versions SET yanked = ?
WHERE crate_id = (SELECT id FROM cargo_crates WHERE repository_id = ? AND name_lower = ?)
  AND version = ?
`

type SetCargoYankedParams struct {
	Yanked       int64  `json:"yanked"`
	RepositoryID string `json:"repository_id"`
	NameLower    string `json:"name_lower"`
	Version      string `json:"version"`
}

func (q *Queries) SetCargoYanked(ctx context.Context, arg SetCargoYankedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCargoYanked,
		arg.Yanked,
		arg.RepositoryID,
		arg.NameLower,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertCargoCrate = `-- name: UpsertCargoCrate :one
INSERT INTO cargo_crates (id, repository_id, name, name_lower, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (repository_id, name_lower)
DO UPDATE SET updated_at = excluded.updated_at, name = excluded.name
RETURNING id
`

type UpsertCargoCrateParams struct {
	ID           string `json:"id"`
	RepositoryID string `json:"repository_id"`
	Name         string `json:"name"`
	NameLower    string `json:"name_lower"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

// Ensure the crate row for (repository, lowercased name) exists, returning its id.
func (q *Queries) UpsertCargoCrate(ctx context.Context, arg UpsertCargoCrateParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertCargoCrate,
		arg.ID,
		arg.RepositoryID,
		arg.Name,
		arg.NameLower,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
