// Package db is the metadata store: it opens the database (SQLite by default,
// Postgres later behind the same interface), runs embedded migrations, and
// exposes typed queries generated by sqlc. It is the only package that knows
// SQL or driver specifics; everything above it depends on the generated
// Querier and the domain services built on top.
package db
