// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generic.sql

package db

import (
	"context"
)

const deleteGenericFile = `-- name: DeleteGenericFile :execrows
DELETE FROM generic_files
WHERE repository_id = ? AND path = ?
`

type DeleteGenericFileParams struct {
	RepositoryID string `json:"repository_id"`
	Path         string `json:"path"`
}

func (q *Queries) DeleteGenericFile(ctx context.Context, arg DeleteGenericFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGenericFile, arg.RepositoryID, arg.Path)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getGenericFile = `-- name: GetGenericFile :one
SELECT id, repository_id, path, blob_digest, size, sha256, sha1, md5, created_at, updated_at FROM generic_files
WHERE repository_id = ? AND path = ?
`

type GetGenericFileParams struct {
	RepositoryID string `json:"repository_id"`
	Path         string `json:"path"`
}

func (q *Queries) GetGenericFile(ctx context.Context, arg GetGenericFileParams) (GenericFile, error) {
	row := q.db.QueryRowContext(ctx, getGenericFile, arg.RepositoryID, arg.Path)
	var i GenericFile
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Path,
		&i.BlobDigest,
		&i.Size,
		&i.Sha256,
		&i.Sha1,
		&i.Md5,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllGenericFiles = `-- name: ListAllGenericFiles :many
SELECT
    p.key        AS project_key,
    p.name       AS project_name,
    r.key        AS repo_key,
    f.path       AS path,
    f.size       AS size,
    CAST(r.mode = 'proxy' AS INTEGER) AS is_proxy,
    f.updated_at AS updated_at
FROM generic_files f
JOIN repositories r ON r.id = f.repository_id
JOIN projects p ON p.id = r.project_id
ORDER BY p.key ASC, r.key ASC, f.path ASC
`

type ListAllGenericFilesRow struct {
	ProjectKey  string `json:"project_key"`
	ProjectName string `json:"project_name"`
	RepoKey     string `json:"repo_key"`
	Path        string `json:"path"`
	Size        int64  `json:"size"`
	IsProxy     int64  `json:"is_proxy"`
	UpdatedAt   string `json:"updated_at"`
}

// Every generic file across all repositories, joined to its repository and
// project, for the registry browser's generic index. is_proxy is 1 for a proxy
// repository.
func (q *Queries) ListAllGenericFiles(ctx context.Context) ([]ListAllGenericFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllGenericFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllGenericFilesRow{}
	for rows.Next() {
		var i ListAllGenericFilesRow
		if err := rows.Scan(
			&i.ProjectKey,
			&i.ProjectName,
			&i.RepoKey,
			&i.Path,
			&i.Size,
			&i.IsProxy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenericBlobDigests = `-- name: ListGenericBlobDigests :many
SELECT DISTINCT blob_digest FROM generic_files
`

// Distinct blob digests every generic file references, for garbage collection to
// mark them alongside OCI manifests and npm tarballs (shared CAS across formats).
func (q *Queries) ListGenericBlobDigests(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listGenericBlobDigests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blob_digest string
		if err := rows.Scan(&blob_digest); err != nil {
			return nil, err
		}
		items = append(items, blob_digest)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGenericFile = `-- name: UpsertGenericFile :exec
INSERT INTO generic_files (id, repository_id, path, blob_digest, size, sha256, sha1, md5, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (repository_id, path)
DO UPDATE SET
    blob_digest = excluded.blob_digest,
    size        = excluded.size,
    sha256      = excluded.sha256,
    sha1        = excluded.sha1,
    md5         = excluded.md5,
    updated_at  = excluded.updated_at
`

type UpsertGenericFileParams struct {
	ID           string `json:"id"`
	RepositoryID string `json:"repository_id"`
	Path         string `json:"path"`
	BlobDigest   string `json:"blob_digest"`
	Size         int64  `json:"size"`
	Sha256       string `json:"sha256"`
	Sha1         string `json:"sha1"`
	Md5          string `json:"md5"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

// Store a file at a path in a repository, replacing any existing file there
// (generic paths are mutable: a re-upload overwrites).
func (q *Queries) UpsertGenericFile(ctx context.Context, arg UpsertGenericFileParams) error {
	_, err := q.db.ExecContext(ctx, upsertGenericFile,
		arg.ID,
		arg.RepositoryID,
		arg.Path,
		arg.BlobDigest,
		arg.Size,
		arg.Sha256,
		arg.Sha1,
		arg.Md5,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
