// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gomod.sql

package db

import (
	"context"
)

const deleteGoFile = `-- name: DeleteGoFile :execrows
DELETE FROM go_files
WHERE repository_id = ? AND path = ?
`

type DeleteGoFileParams struct {
	RepositoryID string `json:"repository_id"`
	Path         string `json:"path"`
}

func (q *Queries) DeleteGoFile(ctx context.Context, arg DeleteGoFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGoFile, arg.RepositoryID, arg.Path)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getGoFile = `-- name: GetGoFile :one
SELECT id, repository_id, module, version, kind, path, blob_digest, size, upstream_url, created_at, updated_at FROM go_files
WHERE repository_id = ? AND path = ?
`

type GetGoFileParams struct {
	RepositoryID string `json:"repository_id"`
	Path         string `json:"path"`
}

func (q *Queries) GetGoFile(ctx context.Context, arg GetGoFileParams) (GoFile, error) {
	row := q.db.QueryRowContext(ctx, getGoFile, arg.RepositoryID, arg.Path)
	var i GoFile
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Module,
		&i.Version,
		&i.Kind,
		&i.Path,
		&i.BlobDigest,
		&i.Size,
		&i.UpstreamUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllGoModules = `-- name: ListAllGoModules :many
SELECT
    p.key         AS project_key,
    p.name        AS project_name,
    r.key         AS repo_key,
    f.module      AS module,
    COUNT(DISTINCT f.version) AS version_count,
    CAST(COALESCE(SUM(f.size), 0) AS INTEGER) AS size_bytes,
    CAST(r.mode = 'proxy' AS INTEGER) AS is_proxy,
    CAST(MAX(f.updated_at) AS TEXT) AS updated_at
FROM go_files f
JOIN repositories r ON r.id = f.repository_id
JOIN projects p ON p.id = r.project_id
GROUP BY r.id, f.module
ORDER BY p.key ASC, r.key ASC, f.module ASC
`

type ListAllGoModulesRow struct {
	ProjectKey   string `json:"project_key"`
	ProjectName  string `json:"project_name"`
	RepoKey      string `json:"repo_key"`
	Module       string `json:"module"`
	VersionCount int64  `json:"version_count"`
	SizeBytes    int64  `json:"size_bytes"`
	IsProxy      int64  `json:"is_proxy"`
	UpdatedAt    string `json:"updated_at"`
}

// Every cached Go module across all repositories, with version count, total
// cached size, and a proxy flag, for the browser's project-grouped index.
func (q *Queries) ListAllGoModules(ctx context.Context) ([]ListAllGoModulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllGoModules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllGoModulesRow{}
	for rows.Next() {
		var i ListAllGoModulesRow
		if err := rows.Scan(
			&i.ProjectKey,
			&i.ProjectName,
			&i.RepoKey,
			&i.Module,
			&i.VersionCount,
			&i.SizeBytes,
			&i.IsProxy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoBlobDigests = `-- name: ListGoBlobDigests :many
SELECT DISTINCT blob_digest FROM go_files WHERE blob_digest != ''
`

// Distinct blob digests every cached Go file references, for garbage collection.
func (q *Queries) ListGoBlobDigests(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listGoBlobDigests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blob_digest string
		if err := rows.Scan(&blob_digest); err != nil {
			return nil, err
		}
		items = append(items, blob_digest)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoFilesForModule = `-- name: ListGoFilesForModule :many
SELECT module, version, kind, size, created_at
FROM go_files
WHERE repository_id = ? AND module = ?
ORDER BY version DESC, kind ASC
`

type ListGoFilesForModuleParams struct {
	RepositoryID string `json:"repository_id"`
	Module       string `json:"module"`
}

type ListGoFilesForModuleRow struct {
	Module    string `json:"module"`
	Version   string `json:"version"`
	Kind      string `json:"kind"`
	Size      int64  `json:"size"`
	CreatedAt string `json:"created_at"`
}

// Every cached file of one module, for its detail page.
func (q *Queries) ListGoFilesForModule(ctx context.Context, arg ListGoFilesForModuleParams) ([]ListGoFilesForModuleRow, error) {
	rows, err := q.db.QueryContext(ctx, listGoFilesForModule, arg.RepositoryID, arg.Module)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoFilesForModuleRow{}
	for rows.Next() {
		var i ListGoFilesForModuleRow
		if err := rows.Scan(
			&i.Module,
			&i.Version,
			&i.Kind,
			&i.Size,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoFilesForRetention = `-- name: ListGoFilesForRetention :many
SELECT module AS module, version AS version, path AS path, created_at AS created_at
FROM go_files
WHERE repository_id = ?
ORDER BY module ASC, created_at DESC
`

type ListGoFilesForRetentionRow struct {
	Module    string `json:"module"`
	Version   string `json:"version"`
	Path      string `json:"path"`
	CreatedAt string `json:"created_at"`
}

// Every cached file in a repository, grouped by module and newest first, for
// keep-last-N-versions pruning.
func (q *Queries) ListGoFilesForRetention(ctx context.Context, repositoryID string) ([]ListGoFilesForRetentionRow, error) {
	rows, err := q.db.QueryContext(ctx, listGoFilesForRetention, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoFilesForRetentionRow{}
	for rows.Next() {
		var i ListGoFilesForRetentionRow
		if err := rows.Scan(
			&i.Module,
			&i.Version,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGoFile = `-- name: UpsertGoFile :exec
INSERT INTO go_files (id, repository_id, module, version, kind, path, blob_digest, size, upstream_url, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (repository_id, path)
DO UPDATE SET
    module      = excluded.module,
    version     = excluded.version,
    kind        = excluded.kind,
    blob_digest = excluded.blob_digest,
    size        = excluded.size,
    upstream_url = excluded.upstream_url,
    updated_at  = excluded.updated_at
`

type UpsertGoFileParams struct {
	ID           string `json:"id"`
	RepositoryID string `json:"repository_id"`
	Module       string `json:"module"`
	Version      string `json:"version"`
	Kind         string `json:"kind"`
	Path         string `json:"path"`
	BlobDigest   string `json:"blob_digest"`
	Size         int64  `json:"size"`
	UpstreamUrl  string `json:"upstream_url"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

// Record a cached, immutable Go module file (info, mod, or zip) at its escaped
// request path, filling the blob on first fetch.
func (q *Queries) UpsertGoFile(ctx context.Context, arg UpsertGoFileParams) error {
	_, err := q.db.ExecContext(ctx, upsertGoFile,
		arg.ID,
		arg.RepositoryID,
		arg.Module,
		arg.Version,
		arg.Kind,
		arg.Path,
		arg.BlobDigest,
		arg.Size,
		arg.UpstreamUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
