// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maven.sql

package db

import (
	"context"
)

const deleteMavenFile = `-- name: DeleteMavenFile :execrows
DELETE FROM maven_files
WHERE repository_id = ? AND path = ?
`

type DeleteMavenFileParams struct {
	RepositoryID string `json:"repository_id"`
	Path         string `json:"path"`
}

func (q *Queries) DeleteMavenFile(ctx context.Context, arg DeleteMavenFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMavenFile, arg.RepositoryID, arg.Path)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMavenFile = `-- name: GetMavenFile :one
SELECT id, repository_id, path, group_id, artifact_id, version, filename, is_metadata, blob_digest, size, sha1, md5, upstream_url, created_at, updated_at FROM maven_files
WHERE repository_id = ? AND path = ?
`

type GetMavenFileParams struct {
	RepositoryID string `json:"repository_id"`
	Path         string `json:"path"`
}

func (q *Queries) GetMavenFile(ctx context.Context, arg GetMavenFileParams) (MavenFile, error) {
	row := q.db.QueryRowContext(ctx, getMavenFile, arg.RepositoryID, arg.Path)
	var i MavenFile
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Path,
		&i.GroupID,
		&i.ArtifactID,
		&i.Version,
		&i.Filename,
		&i.IsMetadata,
		&i.BlobDigest,
		&i.Size,
		&i.Sha1,
		&i.Md5,
		&i.UpstreamUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllMavenArtifacts = `-- name: ListAllMavenArtifacts :many
SELECT
    p.key         AS project_key,
    p.name        AS project_name,
    r.key         AS repo_key,
    f.group_id    AS group_id,
    f.artifact_id AS artifact_id,
    COUNT(DISTINCT CASE WHEN f.is_metadata = 0 AND f.version != '' THEN f.version END) AS version_count,
    CAST(COALESCE(SUM(f.size), 0) AS INTEGER) AS size_bytes,
    CAST(r.mode = 'proxy' AS INTEGER) AS is_proxy,
    CAST(MAX(f.updated_at) AS TEXT) AS updated_at
FROM maven_files f
JOIN repositories r ON r.id = f.repository_id
JOIN projects p ON p.id = r.project_id
WHERE f.group_id != '' AND f.artifact_id != ''
GROUP BY r.id, f.group_id, f.artifact_id
ORDER BY p.key ASC, r.key ASC, f.group_id ASC, f.artifact_id ASC
`

type ListAllMavenArtifactsRow struct {
	ProjectKey   string `json:"project_key"`
	ProjectName  string `json:"project_name"`
	RepoKey      string `json:"repo_key"`
	GroupID      string `json:"group_id"`
	ArtifactID   string `json:"artifact_id"`
	VersionCount int64  `json:"version_count"`
	SizeBytes    int64  `json:"size_bytes"`
	IsProxy      int64  `json:"is_proxy"`
	UpdatedAt    string `json:"updated_at"`
}

// Every Maven artifact (group:artifact) across all repositories, with its version
// count, total cached size, and a proxy flag, for the browser's project-grouped
// index. Metadata files count toward size but not toward the version count.
func (q *Queries) ListAllMavenArtifacts(ctx context.Context) ([]ListAllMavenArtifactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllMavenArtifacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllMavenArtifactsRow{}
	for rows.Next() {
		var i ListAllMavenArtifactsRow
		if err := rows.Scan(
			&i.ProjectKey,
			&i.ProjectName,
			&i.RepoKey,
			&i.GroupID,
			&i.ArtifactID,
			&i.VersionCount,
			&i.SizeBytes,
			&i.IsProxy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMavenBlobDigests = `-- name: ListMavenBlobDigests :many
SELECT DISTINCT blob_digest FROM maven_files WHERE blob_digest != ''
`

// Distinct blob digests every cached/uploaded Maven file references, for garbage
// collection to mark them alongside other formats. Empty (uncached) rows excluded.
func (q *Queries) ListMavenBlobDigests(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMavenBlobDigests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blob_digest string
		if err := rows.Scan(&blob_digest); err != nil {
			return nil, err
		}
		items = append(items, blob_digest)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMavenFilesForArtifact = `-- name: ListMavenFilesForArtifact :many
SELECT path, group_id, artifact_id, version, filename, is_metadata, size, sha1
FROM maven_files
WHERE repository_id = ? AND group_id = ? AND artifact_id = ?
ORDER BY version DESC, filename ASC
`

type ListMavenFilesForArtifactParams struct {
	RepositoryID string `json:"repository_id"`
	GroupID      string `json:"group_id"`
	ArtifactID   string `json:"artifact_id"`
}

type ListMavenFilesForArtifactRow struct {
	Path       string `json:"path"`
	GroupID    string `json:"group_id"`
	ArtifactID string `json:"artifact_id"`
	Version    string `json:"version"`
	Filename   string `json:"filename"`
	IsMetadata int64  `json:"is_metadata"`
	Size       int64  `json:"size"`
	Sha1       string `json:"sha1"`
}

// Every file of one artifact (group + artifact), for its detail page.
func (q *Queries) ListMavenFilesForArtifact(ctx context.Context, arg ListMavenFilesForArtifactParams) ([]ListMavenFilesForArtifactRow, error) {
	rows, err := q.db.QueryContext(ctx, listMavenFilesForArtifact, arg.RepositoryID, arg.GroupID, arg.ArtifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMavenFilesForArtifactRow{}
	for rows.Next() {
		var i ListMavenFilesForArtifactRow
		if err := rows.Scan(
			&i.Path,
			&i.GroupID,
			&i.ArtifactID,
			&i.Version,
			&i.Filename,
			&i.IsMetadata,
			&i.Size,
			&i.Sha1,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMavenFilesForRetention = `-- name: ListMavenFilesForRetention :many
SELECT group_id AS group_id, artifact_id AS artifact_id, version AS version, path AS path, created_at AS created_at
FROM maven_files
WHERE repository_id = ? AND is_metadata = 0 AND version != ''
ORDER BY group_id ASC, artifact_id ASC, created_at DESC
`

type ListMavenFilesForRetentionRow struct {
	GroupID    string `json:"group_id"`
	ArtifactID string `json:"artifact_id"`
	Version    string `json:"version"`
	Path       string `json:"path"`
	CreatedAt  string `json:"created_at"`
}

// Every non-metadata file in a repository, grouped by artifact and newest first,
// for keep-last-N-versions pruning. Metadata files are excluded from counting.
func (q *Queries) ListMavenFilesForRetention(ctx context.Context, repositoryID string) ([]ListMavenFilesForRetentionRow, error) {
	rows, err := q.db.QueryContext(ctx, listMavenFilesForRetention, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMavenFilesForRetentionRow{}
	for rows.Next() {
		var i ListMavenFilesForRetentionRow
		if err := rows.Scan(
			&i.GroupID,
			&i.ArtifactID,
			&i.Version,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMavenFile = `-- name: UpsertMavenFile :exec
INSERT INTO maven_files (id, repository_id, path, group_id, artifact_id, version, filename, is_metadata, blob_digest, size, sha1, md5, upstream_url, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (repository_id, path)
DO UPDATE SET
    group_id    = excluded.group_id,
    artifact_id = excluded.artifact_id,
    version     = excluded.version,
    filename    = excluded.filename,
    is_metadata = excluded.is_metadata,
    blob_digest = excluded.blob_digest,
    size        = excluded.size,
    sha1        = excluded.sha1,
    md5         = excluded.md5,
    upstream_url = excluded.upstream_url,
    updated_at  = excluded.updated_at
`

type UpsertMavenFileParams struct {
	ID           string `json:"id"`
	RepositoryID string `json:"repository_id"`
	Path         string `json:"path"`
	GroupID      string `json:"group_id"`
	ArtifactID   string `json:"artifact_id"`
	Version      string `json:"version"`
	Filename     string `json:"filename"`
	IsMetadata   int64  `json:"is_metadata"`
	BlobDigest   string `json:"blob_digest"`
	Size         int64  `json:"size"`
	Sha1         string `json:"sha1"`
	Md5          string `json:"md5"`
	UpstreamUrl  string `json:"upstream_url"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

// Store a file at a path in a repository, replacing any existing file there
// (Maven paths are mutable: SNAPSHOT redeploys and metadata updates overwrite).
func (q *Queries) UpsertMavenFile(ctx context.Context, arg UpsertMavenFileParams) error {
	_, err := q.db.ExecContext(ctx, upsertMavenFile,
		arg.ID,
		arg.RepositoryID,
		arg.Path,
		arg.GroupID,
		arg.ArtifactID,
		arg.Version,
		arg.Filename,
		arg.IsMetadata,
		arg.BlobDigest,
		arg.Size,
		arg.Sha1,
		arg.Md5,
		arg.UpstreamUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
