// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package db

import (
	"context"
)

const deleteProjectMember = `-- name: DeleteProjectMember :execrows
DELETE FROM project_members
WHERE project_id = ? AND user_id = ?
`

type DeleteProjectMemberParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) DeleteProjectMember(ctx context.Context, arg DeleteProjectMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProjectMember, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProjectMemberRole = `-- name: GetProjectMemberRole :one
SELECT role FROM project_members
WHERE project_id = ? AND user_id = ?
`

type GetProjectMemberRoleParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

// The user's role in a project; no row means no membership (no access).
func (q *Queries) GetProjectMemberRole(ctx context.Context, arg GetProjectMemberRoleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getProjectMemberRole, arg.ProjectID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT m.user_id, u.username, u.email, m.role, m.created_at, m.updated_at
FROM project_members m
JOIN users u ON u.id = m.user_id
WHERE m.project_id = ?
ORDER BY u.username ASC
`

type ListProjectMembersRow struct {
	UserID    string `json:"user_id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Role      string `json:"role"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// Every member of a project with their account, ordered by username.
func (q *Queries) ListProjectMembers(ctx context.Context, projectID string) ([]ListProjectMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProjectMember = `-- name: UpsertProjectMember :exec
INSERT INTO project_members (project_id, user_id, role, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (project_id, user_id)
DO UPDATE SET role = excluded.role, updated_at = excluded.updated_at
`

type UpsertProjectMemberParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
	Role      string `json:"role"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// Grant a user a role in a project, or change their existing role.
func (q *Queries) UpsertProjectMember(ctx context.Context, arg UpsertProjectMemberParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectMember,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
