// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type ApiToken struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	Name      string         `json:"name"`
	TokenHash string         `json:"token_hash"`
	Prefix    string         `json:"prefix"`
	CreatedAt string         `json:"created_at"`
	ExpiresAt sql.NullString `json:"expires_at"`
}

type AuditLog struct {
	ID         string         `json:"id"`
	ProjectID  sql.NullString `json:"project_id"`
	Actor      string         `json:"actor"`
	Action     string         `json:"action"`
	TargetType string         `json:"target_type"`
	TargetID   string         `json:"target_id"`
	Metadata   string         `json:"metadata"`
	CreatedAt  string         `json:"created_at"`
}

type OciManifest struct {
	ID           string `json:"id"`
	ProjectID    string `json:"project_id"`
	Repository   string `json:"repository"`
	Digest       string `json:"digest"`
	MediaType    string `json:"media_type"`
	Payload      []byte `json:"payload"`
	Size         int64  `json:"size"`
	CreatedAt    string `json:"created_at"`
	Subject      string `json:"subject"`
	ArtifactType string `json:"artifact_type"`
}

type OciTag struct {
	ProjectID  string `json:"project_id"`
	Repository string `json:"repository"`
	Tag        string `json:"tag"`
	Digest     string `json:"digest"`
	UpdatedAt  string `json:"updated_at"`
}

type Project struct {
	ID          string `json:"id"`
	Key         string `json:"key"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type Session struct {
	ID        string `json:"id"`
	TokenHash string `json:"token_hash"`
	UserID    string `json:"user_id"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

type User struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	IsAdmin      int64  `json:"is_admin"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}
