// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type ApiToken struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	Name      string         `json:"name"`
	TokenHash string         `json:"token_hash"`
	Prefix    string         `json:"prefix"`
	CreatedAt string         `json:"created_at"`
	ExpiresAt sql.NullString `json:"expires_at"`
}

type AuditLog struct {
	ID         string         `json:"id"`
	ProjectID  sql.NullString `json:"project_id"`
	Actor      string         `json:"actor"`
	Action     string         `json:"action"`
	TargetType string         `json:"target_type"`
	TargetID   string         `json:"target_id"`
	Metadata   string         `json:"metadata"`
	CreatedAt  string         `json:"created_at"`
}

type CargoCrate struct {
	ID           string `json:"id"`
	RepositoryID string `json:"repository_id"`
	Name         string `json:"name"`
	NameLower    string `json:"name_lower"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type CargoVersion struct {
	ID          string `json:"id"`
	CrateID     string `json:"crate_id"`
	Version     string `json:"version"`
	IndexLine   string `json:"index_line"`
	Cksum       string `json:"cksum"`
	BlobDigest  string `json:"blob_digest"`
	Size        int64  `json:"size"`
	Yanked      int64  `json:"yanked"`
	UpstreamUrl string `json:"upstream_url"`
	CreatedAt   string `json:"created_at"`
}

type GenericFile struct {
	ID           string `json:"id"`
	RepositoryID string `json:"repository_id"`
	Path         string `json:"path"`
	BlobDigest   string `json:"blob_digest"`
	Size         int64  `json:"size"`
	Sha256       string `json:"sha256"`
	Sha1         string `json:"sha1"`
	Md5          string `json:"md5"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type GoFile struct {
	ID           string `json:"id"`
	RepositoryID string `json:"repository_id"`
	Module       string `json:"module"`
	Version      string `json:"version"`
	Kind         string `json:"kind"`
	Path         string `json:"path"`
	BlobDigest   string `json:"blob_digest"`
	Size         int64  `json:"size"`
	UpstreamUrl  string `json:"upstream_url"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type MavenFile struct {
	ID           string `json:"id"`
	RepositoryID string `json:"repository_id"`
	Path         string `json:"path"`
	GroupID      string `json:"group_id"`
	ArtifactID   string `json:"artifact_id"`
	Version      string `json:"version"`
	Filename     string `json:"filename"`
	IsMetadata   int64  `json:"is_metadata"`
	BlobDigest   string `json:"blob_digest"`
	Size         int64  `json:"size"`
	Sha1         string `json:"sha1"`
	Md5          string `json:"md5"`
	UpstreamUrl  string `json:"upstream_url"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type NpmDistTag struct {
	PackageID string `json:"package_id"`
	Tag       string `json:"tag"`
	Version   string `json:"version"`
	UpdatedAt string `json:"updated_at"`
}

type NpmPackage struct {
	ID           string `json:"id"`
	RepositoryID string `json:"repository_id"`
	Name         string `json:"name"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type NpmVersion struct {
	ID            string `json:"id"`
	PackageID     string `json:"package_id"`
	Version       string `json:"version"`
	Manifest      []byte `json:"manifest"`
	TarballDigest string `json:"tarball_digest"`
	TarballSize   int64  `json:"tarball_size"`
	Shasum        string `json:"shasum"`
	Integrity     string `json:"integrity"`
	CreatedAt     string `json:"created_at"`
}

type NugetPackage struct {
	ID           string `json:"id"`
	RepositoryID string `json:"repository_id"`
	IDLower      string `json:"id_lower"`
	IDOriginal   string `json:"id_original"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type NugetVersion struct {
	ID           string `json:"id"`
	PackageID    string `json:"package_id"`
	Version      string `json:"version"`
	VersionLower string `json:"version_lower"`
	NupkgDigest  string `json:"nupkg_digest"`
	NupkgSize    int64  `json:"nupkg_size"`
	Nuspec       []byte `json:"nuspec"`
	CreatedAt    string `json:"created_at"`
}

type OciManifest struct {
	ID           string `json:"id"`
	RepositoryID string `json:"repository_id"`
	Repository   string `json:"repository"`
	Digest       string `json:"digest"`
	MediaType    string `json:"media_type"`
	Payload      []byte `json:"payload"`
	Size         int64  `json:"size"`
	Subject      string `json:"subject"`
	ArtifactType string `json:"artifact_type"`
	CreatedAt    string `json:"created_at"`
}

type OciTag struct {
	RepositoryID string `json:"repository_id"`
	Repository   string `json:"repository"`
	Tag          string `json:"tag"`
	Digest       string `json:"digest"`
	UpdatedAt    string `json:"updated_at"`
}

type Project struct {
	ID              string `json:"id"`
	Key             string `json:"key"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
	AllowAutoCreate int64  `json:"allow_auto_create"`
}

type ProjectMember struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
	Role      string `json:"role"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type PypiFile struct {
	ID             string `json:"id"`
	PackageID      string `json:"package_id"`
	Version        string `json:"version"`
	Filename       string `json:"filename"`
	BlobDigest     string `json:"blob_digest"`
	Size           int64  `json:"size"`
	Sha256         string `json:"sha256"`
	RequiresPython string `json:"requires_python"`
	UpstreamUrl    string `json:"upstream_url"`
	CreatedAt      string `json:"created_at"`
}

type PypiPackage struct {
	ID           string `json:"id"`
	RepositoryID string `json:"repository_id"`
	Name         string `json:"name"`
	NameOriginal string `json:"name_original"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type Repository struct {
	ID               string `json:"id"`
	ProjectID        string `json:"project_id"`
	Key              string `json:"key"`
	Name             string `json:"name"`
	Format           string `json:"format"`
	Mode             string `json:"mode"`
	UpstreamUrl      string `json:"upstream_url"`
	UpstreamUsername string `json:"upstream_username"`
	UpstreamPassword string `json:"upstream_password"`
	KeepLast         int64  `json:"keep_last"`
	DeleteUntagged   int64  `json:"delete_untagged"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
}

type Session struct {
	ID        string `json:"id"`
	TokenHash string `json:"token_hash"`
	UserID    string `json:"user_id"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

type User struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	IsAdmin      int64  `json:"is_admin"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}
