// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: npm.sql

package db

import (
	"context"
)

const deleteNpmDistTag = `-- name: DeleteNpmDistTag :execrows
DELETE FROM npm_dist_tags
WHERE package_id = ? AND tag = ?
`

type DeleteNpmDistTagParams struct {
	PackageID string `json:"package_id"`
	Tag       string `json:"tag"`
}

func (q *Queries) DeleteNpmDistTag(ctx context.Context, arg DeleteNpmDistTagParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNpmDistTag, arg.PackageID, arg.Tag)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getNpmPackage = `-- name: GetNpmPackage :one
SELECT id, project_id, name, created_at, updated_at FROM npm_packages
WHERE project_id = ? AND name = ?
`

type GetNpmPackageParams struct {
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
}

func (q *Queries) GetNpmPackage(ctx context.Context, arg GetNpmPackageParams) (NpmPackage, error) {
	row := q.db.QueryRowContext(ctx, getNpmPackage, arg.ProjectID, arg.Name)
	var i NpmPackage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNpmTarball = `-- name: GetNpmTarball :one
SELECT v.tarball_digest, v.tarball_size
FROM npm_versions v
JOIN npm_packages p ON p.id = v.package_id
WHERE p.project_id = ? AND p.name = ? AND v.version = ?
`

type GetNpmTarballParams struct {
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
	Version   string `json:"version"`
}

type GetNpmTarballRow struct {
	TarballDigest string `json:"tarball_digest"`
	TarballSize   int64  `json:"tarball_size"`
}

// The blob digest and size for one package version's tarball, to serve it.
func (q *Queries) GetNpmTarball(ctx context.Context, arg GetNpmTarballParams) (GetNpmTarballRow, error) {
	row := q.db.QueryRowContext(ctx, getNpmTarball, arg.ProjectID, arg.Name, arg.Version)
	var i GetNpmTarballRow
	err := row.Scan(&i.TarballDigest, &i.TarballSize)
	return i, err
}

const insertNpmVersion = `-- name: InsertNpmVersion :exec
INSERT INTO npm_versions (id, package_id, version, manifest, tarball_digest, tarball_size, shasum, integrity, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (package_id, version) DO NOTHING
`

type InsertNpmVersionParams struct {
	ID            string `json:"id"`
	PackageID     string `json:"package_id"`
	Version       string `json:"version"`
	Manifest      []byte `json:"manifest"`
	TarballDigest string `json:"tarball_digest"`
	TarballSize   int64  `json:"tarball_size"`
	Shasum        string `json:"shasum"`
	Integrity     string `json:"integrity"`
	CreatedAt     string `json:"created_at"`
}

// Store a published version. First-writer-wins: a duplicate (already rejected at
// the handler) is a no-op rather than a transaction error.
func (q *Queries) InsertNpmVersion(ctx context.Context, arg InsertNpmVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertNpmVersion,
		arg.ID,
		arg.PackageID,
		arg.Version,
		arg.Manifest,
		arg.TarballDigest,
		arg.TarballSize,
		arg.Shasum,
		arg.Integrity,
		arg.CreatedAt,
	)
	return err
}

const listAllNpmPackages = `-- name: ListAllNpmPackages :many
SELECT
    p.key        AS project_key,
    p.name       AS project_name,
    pkg.name     AS package_name,
    COUNT(v.id)  AS version_count,
    CAST(COALESCE(SUM(v.tarball_size), 0) AS INTEGER) AS size_bytes,
    CAST(rp.project_id IS NOT NULL AS INTEGER) AS is_proxy,
    pkg.updated_at AS updated_at
FROM npm_packages pkg
JOIN projects p ON p.id = pkg.project_id
LEFT JOIN registry_proxies rp ON rp.project_id = pkg.project_id
LEFT JOIN npm_versions v ON v.package_id = pkg.id
GROUP BY pkg.id
ORDER BY p.key ASC, pkg.name ASC
`

type ListAllNpmPackagesRow struct {
	ProjectKey   string `json:"project_key"`
	ProjectName  string `json:"project_name"`
	PackageName  string `json:"package_name"`
	VersionCount int64  `json:"version_count"`
	SizeBytes    int64  `json:"size_bytes"`
	IsProxy      int64  `json:"is_proxy"`
	UpdatedAt    string `json:"updated_at"`
}

// Every npm package across all projects, with version count, total tarball size,
// and a proxy flag, for the registry browser's package index. is_proxy is 1 when
// the package's project is a pull-through mirror.
func (q *Queries) ListAllNpmPackages(ctx context.Context) ([]ListAllNpmPackagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllNpmPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllNpmPackagesRow{}
	for rows.Next() {
		var i ListAllNpmPackagesRow
		if err := rows.Scan(
			&i.ProjectKey,
			&i.ProjectName,
			&i.PackageName,
			&i.VersionCount,
			&i.SizeBytes,
			&i.IsProxy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNpmDistTags = `-- name: ListNpmDistTags :many
SELECT t.tag, t.version
FROM npm_dist_tags t
JOIN npm_packages p ON p.id = t.package_id
WHERE p.project_id = ? AND p.name = ?
`

type ListNpmDistTagsParams struct {
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
}

type ListNpmDistTagsRow struct {
	Tag     string `json:"tag"`
	Version string `json:"version"`
}

func (q *Queries) ListNpmDistTags(ctx context.Context, arg ListNpmDistTagsParams) ([]ListNpmDistTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNpmDistTags, arg.ProjectID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNpmDistTagsRow{}
	for rows.Next() {
		var i ListNpmDistTagsRow
		if err := rows.Scan(&i.Tag, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNpmTarballDigests = `-- name: ListNpmTarballDigests :many
SELECT DISTINCT tarball_digest FROM npm_versions
`

// Distinct tarball digests every npm version references, for garbage collection
// to mark them alongside OCI blobs. Blobs are a shared CAS spanning all formats.
func (q *Queries) ListNpmTarballDigests(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listNpmTarballDigests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tarball_digest string
		if err := rows.Scan(&tarball_digest); err != nil {
			return nil, err
		}
		items = append(items, tarball_digest)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNpmVersions = `-- name: ListNpmVersions :many
SELECT v.version, v.manifest, v.tarball_digest, v.tarball_size, v.shasum, v.integrity, v.created_at
FROM npm_versions v
JOIN npm_packages p ON p.id = v.package_id
WHERE p.project_id = ? AND p.name = ?
ORDER BY v.created_at ASC
`

type ListNpmVersionsParams struct {
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
}

type ListNpmVersionsRow struct {
	Version       string `json:"version"`
	Manifest      []byte `json:"manifest"`
	TarballDigest string `json:"tarball_digest"`
	TarballSize   int64  `json:"tarball_size"`
	Shasum        string `json:"shasum"`
	Integrity     string `json:"integrity"`
	CreatedAt     string `json:"created_at"`
}

// Every published version of a package, oldest first, with the verbatim version
// metadata and its tarball's digests, so the packument can be rebuilt.
func (q *Queries) ListNpmVersions(ctx context.Context, arg ListNpmVersionsParams) ([]ListNpmVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNpmVersions, arg.ProjectID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNpmVersionsRow{}
	for rows.Next() {
		var i ListNpmVersionsRow
		if err := rows.Scan(
			&i.Version,
			&i.Manifest,
			&i.TarballDigest,
			&i.TarballSize,
			&i.Shasum,
			&i.Integrity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const npmVersionExists = `-- name: NpmVersionExists :one
SELECT COUNT(*) FROM npm_versions v
JOIN npm_packages p ON p.id = v.package_id
WHERE p.project_id = ? AND p.name = ? AND v.version = ?
`

type NpmVersionExistsParams struct {
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
	Version   string `json:"version"`
}

// Whether a specific version is already published. npm forbids overwriting a
// published version, so the handler rejects a re-publish before inserting.
func (q *Queries) NpmVersionExists(ctx context.Context, arg NpmVersionExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, npmVersionExists, arg.ProjectID, arg.Name, arg.Version)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertNpmDistTag = `-- name: UpsertNpmDistTag :exec
INSERT INTO npm_dist_tags (package_id, tag, version, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (package_id, tag)
DO UPDATE SET version = excluded.version, updated_at = excluded.updated_at
`

type UpsertNpmDistTagParams struct {
	PackageID string `json:"package_id"`
	Tag       string `json:"tag"`
	Version   string `json:"version"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) UpsertNpmDistTag(ctx context.Context, arg UpsertNpmDistTagParams) error {
	_, err := q.db.ExecContext(ctx, upsertNpmDistTag,
		arg.PackageID,
		arg.Tag,
		arg.Version,
		arg.UpdatedAt,
	)
	return err
}

const upsertNpmPackage = `-- name: UpsertNpmPackage :one
INSERT INTO npm_packages (id, project_id, name, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (project_id, name)
DO UPDATE SET updated_at = excluded.updated_at
RETURNING id
`

type UpsertNpmPackageParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// Ensure the package row for (project, name) exists, returning its id.
// Publishing a new version of an existing package just bumps updated_at.
func (q *Queries) UpsertNpmPackage(ctx context.Context, arg UpsertNpmPackageParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertNpmPackage,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
