// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nuget.sql

package db

import (
	"context"
)

const deleteNugetVersion = `-- name: DeleteNugetVersion :execrows
DELETE FROM nuget_versions
WHERE package_id = (SELECT id FROM nuget_packages WHERE repository_id = ? AND id_lower = ?)
  AND version_lower = ?
`

type DeleteNugetVersionParams struct {
	RepositoryID string `json:"repository_id"`
	IDLower      string `json:"id_lower"`
	VersionLower string `json:"version_lower"`
}

func (q *Queries) DeleteNugetVersion(ctx context.Context, arg DeleteNugetVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNugetVersion, arg.RepositoryID, arg.IDLower, arg.VersionLower)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getNugetNupkg = `-- name: GetNugetNupkg :one
SELECT v.nupkg_digest, v.nupkg_size
FROM nuget_versions v
JOIN nuget_packages p ON p.id = v.package_id
WHERE p.repository_id = ? AND p.id_lower = ? AND v.version_lower = ?
`

type GetNugetNupkgParams struct {
	RepositoryID string `json:"repository_id"`
	IDLower      string `json:"id_lower"`
	VersionLower string `json:"version_lower"`
}

type GetNugetNupkgRow struct {
	NupkgDigest string `json:"nupkg_digest"`
	NupkgSize   int64  `json:"nupkg_size"`
}

// The blob digest and size for one version's .nupkg, to serve it.
func (q *Queries) GetNugetNupkg(ctx context.Context, arg GetNugetNupkgParams) (GetNugetNupkgRow, error) {
	row := q.db.QueryRowContext(ctx, getNugetNupkg, arg.RepositoryID, arg.IDLower, arg.VersionLower)
	var i GetNugetNupkgRow
	err := row.Scan(&i.NupkgDigest, &i.NupkgSize)
	return i, err
}

const getNugetPackage = `-- name: GetNugetPackage :one
SELECT id, repository_id, id_lower, id_original, created_at, updated_at FROM nuget_packages
WHERE repository_id = ? AND id_lower = ?
`

type GetNugetPackageParams struct {
	RepositoryID string `json:"repository_id"`
	IDLower      string `json:"id_lower"`
}

func (q *Queries) GetNugetPackage(ctx context.Context, arg GetNugetPackageParams) (NugetPackage, error) {
	row := q.db.QueryRowContext(ctx, getNugetPackage, arg.RepositoryID, arg.IDLower)
	var i NugetPackage
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.IDLower,
		&i.IDOriginal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNugetVersion = `-- name: InsertNugetVersion :exec
INSERT INTO nuget_versions (id, package_id, version, version_lower, nupkg_digest, nupkg_size, nuspec, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (package_id, version_lower) DO NOTHING
`

type InsertNugetVersionParams struct {
	ID           string `json:"id"`
	PackageID    string `json:"package_id"`
	Version      string `json:"version"`
	VersionLower string `json:"version_lower"`
	NupkgDigest  string `json:"nupkg_digest"`
	NupkgSize    int64  `json:"nupkg_size"`
	Nuspec       []byte `json:"nuspec"`
	CreatedAt    string `json:"created_at"`
}

func (q *Queries) InsertNugetVersion(ctx context.Context, arg InsertNugetVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertNugetVersion,
		arg.ID,
		arg.PackageID,
		arg.Version,
		arg.VersionLower,
		arg.NupkgDigest,
		arg.NupkgSize,
		arg.Nuspec,
		arg.CreatedAt,
	)
	return err
}

const listAllNugetPackages = `-- name: ListAllNugetPackages :many
SELECT
    p.key         AS project_key,
    p.name        AS project_name,
    r.key         AS repo_key,
    pkg.id_original AS package_id,
    COUNT(v.id)   AS version_count,
    CAST(COALESCE(SUM(v.nupkg_size), 0) AS INTEGER) AS size_bytes,
    CAST(r.mode = 'proxy' AS INTEGER) AS is_proxy,
    pkg.updated_at AS updated_at
FROM nuget_packages pkg
JOIN repositories r ON r.id = pkg.repository_id
JOIN projects p ON p.id = r.project_id
LEFT JOIN nuget_versions v ON v.package_id = pkg.id
GROUP BY pkg.id
ORDER BY p.key ASC, r.key ASC, pkg.id_lower ASC
`

type ListAllNugetPackagesRow struct {
	ProjectKey   string `json:"project_key"`
	ProjectName  string `json:"project_name"`
	RepoKey      string `json:"repo_key"`
	PackageID    string `json:"package_id"`
	VersionCount int64  `json:"version_count"`
	SizeBytes    int64  `json:"size_bytes"`
	IsProxy      int64  `json:"is_proxy"`
	UpdatedAt    string `json:"updated_at"`
}

// Every NuGet package across all repositories, joined to its repository and
// project, with version count, total nupkg size, and a proxy flag.
func (q *Queries) ListAllNugetPackages(ctx context.Context) ([]ListAllNugetPackagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllNugetPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllNugetPackagesRow{}
	for rows.Next() {
		var i ListAllNugetPackagesRow
		if err := rows.Scan(
			&i.ProjectKey,
			&i.ProjectName,
			&i.RepoKey,
			&i.PackageID,
			&i.VersionCount,
			&i.SizeBytes,
			&i.IsProxy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNugetBlobDigests = `-- name: ListNugetBlobDigests :many
SELECT DISTINCT nupkg_digest FROM nuget_versions
`

// Distinct nupkg digests every version references, for garbage collection to
// mark them alongside the other formats (shared CAS).
func (q *Queries) ListNugetBlobDigests(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listNugetBlobDigests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var nupkg_digest string
		if err := rows.Scan(&nupkg_digest); err != nil {
			return nil, err
		}
		items = append(items, nupkg_digest)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNugetVersions = `-- name: ListNugetVersions :many
SELECT v.version, v.version_lower, v.nupkg_digest, v.nupkg_size, v.nuspec, v.created_at
FROM nuget_versions v
JOIN nuget_packages p ON p.id = v.package_id
WHERE p.repository_id = ? AND p.id_lower = ?
ORDER BY v.created_at ASC
`

type ListNugetVersionsParams struct {
	RepositoryID string `json:"repository_id"`
	IDLower      string `json:"id_lower"`
}

type ListNugetVersionsRow struct {
	Version      string `json:"version"`
	VersionLower string `json:"version_lower"`
	NupkgDigest  string `json:"nupkg_digest"`
	NupkgSize    int64  `json:"nupkg_size"`
	Nuspec       []byte `json:"nuspec"`
	CreatedAt    string `json:"created_at"`
}

// Every version of a package, oldest first, with the nuspec and nupkg pointer,
// for the flat-container index, registration, and downloads.
func (q *Queries) ListNugetVersions(ctx context.Context, arg ListNugetVersionsParams) ([]ListNugetVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNugetVersions, arg.RepositoryID, arg.IDLower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNugetVersionsRow{}
	for rows.Next() {
		var i ListNugetVersionsRow
		if err := rows.Scan(
			&i.Version,
			&i.VersionLower,
			&i.NupkgDigest,
			&i.NupkgSize,
			&i.Nuspec,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNugetVersionsForRetention = `-- name: ListNugetVersionsForRetention :many
SELECT p.id_lower AS id_lower, v.version_lower AS version_lower, v.created_at AS created_at
FROM nuget_versions v
JOIN nuget_packages p ON p.id = v.package_id
WHERE p.repository_id = ?
ORDER BY p.id_lower ASC, v.created_at DESC
`

type ListNugetVersionsForRetentionRow struct {
	IDLower      string `json:"id_lower"`
	VersionLower string `json:"version_lower"`
	CreatedAt    string `json:"created_at"`
}

// Every version in a repository, grouped by package and newest first, for
// keep-last-N pruning.
func (q *Queries) ListNugetVersionsForRetention(ctx context.Context, repositoryID string) ([]ListNugetVersionsForRetentionRow, error) {
	rows, err := q.db.QueryContext(ctx, listNugetVersionsForRetention, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNugetVersionsForRetentionRow{}
	for rows.Next() {
		var i ListNugetVersionsForRetentionRow
		if err := rows.Scan(&i.IDLower, &i.VersionLower, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nugetVersionExists = `-- name: NugetVersionExists :one
SELECT COUNT(*) FROM nuget_versions v
JOIN nuget_packages p ON p.id = v.package_id
WHERE p.repository_id = ? AND p.id_lower = ? AND v.version_lower = ?
`

type NugetVersionExistsParams struct {
	RepositoryID string `json:"repository_id"`
	IDLower      string `json:"id_lower"`
	VersionLower string `json:"version_lower"`
}

// Whether a specific version is already pushed. NuGet forbids overwriting a
// published version, so the handler rejects a re-push before inserting.
func (q *Queries) NugetVersionExists(ctx context.Context, arg NugetVersionExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nugetVersionExists, arg.RepositoryID, arg.IDLower, arg.VersionLower)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchNugetPackages = `-- name: SearchNugetPackages :many
SELECT
    pkg.id_original AS id_original,
    pkg.id_lower    AS id_lower,
    COUNT(v.id)     AS version_count,
    pkg.updated_at  AS updated_at
FROM nuget_packages pkg
LEFT JOIN nuget_versions v ON v.package_id = pkg.id
WHERE pkg.repository_id = ? AND pkg.id_lower LIKE ?
GROUP BY pkg.id
ORDER BY pkg.updated_at DESC
LIMIT ?
`

type SearchNugetPackagesParams struct {
	RepositoryID string `json:"repository_id"`
	IDLower      string `json:"id_lower"`
	Limit        int64  `json:"limit"`
}

type SearchNugetPackagesRow struct {
	IDOriginal   string `json:"id_original"`
	IDLower      string `json:"id_lower"`
	VersionCount int64  `json:"version_count"`
	UpdatedAt    string `json:"updated_at"`
}

// Packages in a repository whose id contains the (lowercased) query, newest
// first, for the search resource. An empty query matches all.
func (q *Queries) SearchNugetPackages(ctx context.Context, arg SearchNugetPackagesParams) ([]SearchNugetPackagesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchNugetPackages, arg.RepositoryID, arg.IDLower, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchNugetPackagesRow{}
	for rows.Next() {
		var i SearchNugetPackagesRow
		if err := rows.Scan(
			&i.IDOriginal,
			&i.IDLower,
			&i.VersionCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNugetPackage = `-- name: UpsertNugetPackage :one
INSERT INTO nuget_packages (id, repository_id, id_lower, id_original, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (repository_id, id_lower)
DO UPDATE SET updated_at = excluded.updated_at
RETURNING id
`

type UpsertNugetPackageParams struct {
	ID           string `json:"id"`
	RepositoryID string `json:"repository_id"`
	IDLower      string `json:"id_lower"`
	IDOriginal   string `json:"id_original"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

// Ensure the package row for (repository, id_lower) exists, returning its id.
// Pushing a new version of an existing package bumps updated_at.
func (q *Queries) UpsertNugetPackage(ctx context.Context, arg UpsertNugetPackageParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertNugetPackage,
		arg.ID,
		arg.RepositoryID,
		arg.IDLower,
		arg.IDOriginal,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
