// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oci.sql

package db

import (
	"context"
)

const countRepositories = `-- name: CountRepositories :one
SELECT COUNT(*) FROM (SELECT DISTINCT project_id, repository FROM oci_manifests) AS repos
`

// Distinct repositories across all projects, for the dashboard summary.
func (q *Queries) CountRepositories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRepositories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTags = `-- name: CountTags :one
SELECT COUNT(*) FROM oci_tags
`

func (q *Queries) CountTags(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTags)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteManifest = `-- name: DeleteManifest :execrows
DELETE FROM oci_manifests
WHERE project_id = ? AND repository = ? AND digest = ?
`

type DeleteManifestParams struct {
	ProjectID  string `json:"project_id"`
	Repository string `json:"repository"`
	Digest     string `json:"digest"`
}

func (q *Queries) DeleteManifest(ctx context.Context, arg DeleteManifestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteManifest, arg.ProjectID, arg.Repository, arg.Digest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTag = `-- name: DeleteTag :execrows
DELETE FROM oci_tags
WHERE project_id = ? AND repository = ? AND tag = ?
`

type DeleteTagParams struct {
	ProjectID  string `json:"project_id"`
	Repository string `json:"repository"`
	Tag        string `json:"tag"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTag, arg.ProjectID, arg.Repository, arg.Tag)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTagsForDigest = `-- name: DeleteTagsForDigest :exec
DELETE FROM oci_tags
WHERE project_id = ? AND repository = ? AND digest = ?
`

type DeleteTagsForDigestParams struct {
	ProjectID  string `json:"project_id"`
	Repository string `json:"repository"`
	Digest     string `json:"digest"`
}

func (q *Queries) DeleteTagsForDigest(ctx context.Context, arg DeleteTagsForDigestParams) error {
	_, err := q.db.ExecContext(ctx, deleteTagsForDigest, arg.ProjectID, arg.Repository, arg.Digest)
	return err
}

const getManifest = `-- name: GetManifest :one
SELECT id, project_id, repository, digest, media_type, payload, size, created_at FROM oci_manifests
WHERE project_id = ? AND repository = ? AND digest = ?
`

type GetManifestParams struct {
	ProjectID  string `json:"project_id"`
	Repository string `json:"repository"`
	Digest     string `json:"digest"`
}

func (q *Queries) GetManifest(ctx context.Context, arg GetManifestParams) (OciManifest, error) {
	row := q.db.QueryRowContext(ctx, getManifest, arg.ProjectID, arg.Repository, arg.Digest)
	var i OciManifest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Repository,
		&i.Digest,
		&i.MediaType,
		&i.Payload,
		&i.Size,
		&i.CreatedAt,
	)
	return i, err
}

const getTag = `-- name: GetTag :one
SELECT project_id, repository, tag, digest, updated_at FROM oci_tags
WHERE project_id = ? AND repository = ? AND tag = ?
`

type GetTagParams struct {
	ProjectID  string `json:"project_id"`
	Repository string `json:"repository"`
	Tag        string `json:"tag"`
}

func (q *Queries) GetTag(ctx context.Context, arg GetTagParams) (OciTag, error) {
	row := q.db.QueryRowContext(ctx, getTag, arg.ProjectID, arg.Repository, arg.Tag)
	var i OciTag
	err := row.Scan(
		&i.ProjectID,
		&i.Repository,
		&i.Tag,
		&i.Digest,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllRepositories = `-- name: ListAllRepositories :many
SELECT
    p.key                    AS project_key,
    p.name                   AS project_name,
    m.repository             AS repository,
    COUNT(DISTINCT m.digest) AS manifest_count,
    (SELECT COUNT(*) FROM oci_tags t
       WHERE t.project_id = m.project_id AND t.repository = m.repository) AS tag_count,
    MAX(m.created_at)        AS updated_at
FROM oci_manifests m
JOIN projects p ON p.id = m.project_id
GROUP BY m.project_id, m.repository
ORDER BY p.key ASC, m.repository ASC
`

type ListAllRepositoriesRow struct {
	ProjectKey    string      `json:"project_key"`
	ProjectName   string      `json:"project_name"`
	Repository    string      `json:"repository"`
	ManifestCount int64       `json:"manifest_count"`
	TagCount      int64       `json:"tag_count"`
	UpdatedAt     interface{} `json:"updated_at"`
}

// Every repository across all projects, with tag and manifest counts, for the
// registry browser's project-grouped index. A repository exists once it has at
// least one manifest.
func (q *Queries) ListAllRepositories(ctx context.Context) ([]ListAllRepositoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllRepositoriesRow{}
	for rows.Next() {
		var i ListAllRepositoriesRow
		if err := rows.Scan(
			&i.ProjectKey,
			&i.ProjectName,
			&i.Repository,
			&i.ManifestCount,
			&i.TagCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT tag FROM oci_tags
WHERE project_id = ? AND repository = ? AND tag > ?
ORDER BY tag ASC
LIMIT ?
`

type ListTagsParams struct {
	ProjectID  string `json:"project_id"`
	Repository string `json:"repository"`
	Tag        string `json:"tag"`
	Limit      int64  `json:"limit"`
}

// Keyset pagination on `tag`: the empty string sorts before any tag, so the
// first page and subsequent pages share one query.
func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTags,
		arg.ProjectID,
		arg.Repository,
		arg.Tag,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsWithManifest = `-- name: ListTagsWithManifest :many
SELECT
    t.tag        AS tag,
    t.digest     AS digest,
    t.updated_at AS updated_at,
    m.media_type AS media_type,
    m.size       AS size,
    m.payload    AS payload
FROM oci_tags t
JOIN oci_manifests m
  ON m.project_id = t.project_id AND m.repository = t.repository AND m.digest = t.digest
WHERE t.project_id = ? AND t.repository = ?
ORDER BY t.updated_at DESC, t.tag ASC
`

type ListTagsWithManifestParams struct {
	ProjectID  string `json:"project_id"`
	Repository string `json:"repository"`
}

type ListTagsWithManifestRow struct {
	Tag       string `json:"tag"`
	Digest    string `json:"digest"`
	UpdatedAt string `json:"updated_at"`
	MediaType string `json:"media_type"`
	Size      int64  `json:"size"`
	Payload   []byte `json:"payload"`
}

// Tags in a repository joined to the manifest each points at, so the browser can
// show media type and size without a second round-trip. Newest push first.
func (q *Queries) ListTagsWithManifest(ctx context.Context, arg ListTagsWithManifestParams) ([]ListTagsWithManifestRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsWithManifest, arg.ProjectID, arg.Repository)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsWithManifestRow{}
	for rows.Next() {
		var i ListTagsWithManifestRow
		if err := rows.Scan(
			&i.Tag,
			&i.Digest,
			&i.UpdatedAt,
			&i.MediaType,
			&i.Size,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manifestExists = `-- name: ManifestExists :one
SELECT COUNT(*) FROM oci_manifests
WHERE project_id = ? AND repository = ? AND digest = ?
`

type ManifestExistsParams struct {
	ProjectID  string `json:"project_id"`
	Repository string `json:"repository"`
	Digest     string `json:"digest"`
}

func (q *Queries) ManifestExists(ctx context.Context, arg ManifestExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, manifestExists, arg.ProjectID, arg.Repository, arg.Digest)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertManifest = `-- name: UpsertManifest :exec
INSERT INTO oci_manifests (id, project_id, repository, digest, media_type, payload, size, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (project_id, repository, digest) DO NOTHING
`

type UpsertManifestParams struct {
	ID         string `json:"id"`
	ProjectID  string `json:"project_id"`
	Repository string `json:"repository"`
	Digest     string `json:"digest"`
	MediaType  string `json:"media_type"`
	Payload    []byte `json:"payload"`
	Size       int64  `json:"size"`
	CreatedAt  string `json:"created_at"`
}

// Store a manifest by digest. Re-pushing identical content is a no-op, so an
// image can be tagged repeatedly without duplicating the payload.
func (q *Queries) UpsertManifest(ctx context.Context, arg UpsertManifestParams) error {
	_, err := q.db.ExecContext(ctx, upsertManifest,
		arg.ID,
		arg.ProjectID,
		arg.Repository,
		arg.Digest,
		arg.MediaType,
		arg.Payload,
		arg.Size,
		arg.CreatedAt,
	)
	return err
}

const upsertTag = `-- name: UpsertTag :exec
INSERT INTO oci_tags (project_id, repository, tag, digest, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (project_id, repository, tag)
DO UPDATE SET digest = excluded.digest, updated_at = excluded.updated_at
`

type UpsertTagParams struct {
	ProjectID  string `json:"project_id"`
	Repository string `json:"repository"`
	Tag        string `json:"tag"`
	Digest     string `json:"digest"`
	UpdatedAt  string `json:"updated_at"`
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) error {
	_, err := q.db.ExecContext(ctx, upsertTag,
		arg.ProjectID,
		arg.Repository,
		arg.Tag,
		arg.Digest,
		arg.UpdatedAt,
	)
	return err
}
