// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oci.sql

package db

import (
	"context"
)

const countRepositories = `-- name: CountRepositories :one
SELECT COUNT(*) FROM (SELECT DISTINCT repository_id, repository FROM oci_manifests) AS repos
`

// Distinct images across all repositories, for the dashboard summary.
func (q *Queries) CountRepositories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRepositories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTags = `-- name: CountTags :one
SELECT COUNT(*) FROM oci_tags
`

func (q *Queries) CountTags(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTags)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteManifest = `-- name: DeleteManifest :execrows
DELETE FROM oci_manifests
WHERE repository_id = ? AND repository = ? AND digest = ?
`

type DeleteManifestParams struct {
	RepositoryID string `json:"repository_id"`
	Repository   string `json:"repository"`
	Digest       string `json:"digest"`
}

func (q *Queries) DeleteManifest(ctx context.Context, arg DeleteManifestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteManifest, arg.RepositoryID, arg.Repository, arg.Digest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTag = `-- name: DeleteTag :execrows
DELETE FROM oci_tags
WHERE repository_id = ? AND repository = ? AND tag = ?
`

type DeleteTagParams struct {
	RepositoryID string `json:"repository_id"`
	Repository   string `json:"repository"`
	Tag          string `json:"tag"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTag, arg.RepositoryID, arg.Repository, arg.Tag)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTagsForDigest = `-- name: DeleteTagsForDigest :exec
DELETE FROM oci_tags
WHERE repository_id = ? AND repository = ? AND digest = ?
`

type DeleteTagsForDigestParams struct {
	RepositoryID string `json:"repository_id"`
	Repository   string `json:"repository"`
	Digest       string `json:"digest"`
}

func (q *Queries) DeleteTagsForDigest(ctx context.Context, arg DeleteTagsForDigestParams) error {
	_, err := q.db.ExecContext(ctx, deleteTagsForDigest, arg.RepositoryID, arg.Repository, arg.Digest)
	return err
}

const getManifest = `-- name: GetManifest :one
SELECT id, repository_id, repository, digest, media_type, payload, size, subject, artifact_type, created_at FROM oci_manifests
WHERE repository_id = ? AND repository = ? AND digest = ?
`

type GetManifestParams struct {
	RepositoryID string `json:"repository_id"`
	Repository   string `json:"repository"`
	Digest       string `json:"digest"`
}

func (q *Queries) GetManifest(ctx context.Context, arg GetManifestParams) (OciManifest, error) {
	row := q.db.QueryRowContext(ctx, getManifest, arg.RepositoryID, arg.Repository, arg.Digest)
	var i OciManifest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Repository,
		&i.Digest,
		&i.MediaType,
		&i.Payload,
		&i.Size,
		&i.Subject,
		&i.ArtifactType,
		&i.CreatedAt,
	)
	return i, err
}

const getTag = `-- name: GetTag :one
SELECT repository_id, repository, tag, digest, updated_at FROM oci_tags
WHERE repository_id = ? AND repository = ? AND tag = ?
`

type GetTagParams struct {
	RepositoryID string `json:"repository_id"`
	Repository   string `json:"repository"`
	Tag          string `json:"tag"`
}

func (q *Queries) GetTag(ctx context.Context, arg GetTagParams) (OciTag, error) {
	row := q.db.QueryRowContext(ctx, getTag, arg.RepositoryID, arg.Repository, arg.Tag)
	var i OciTag
	err := row.Scan(
		&i.RepositoryID,
		&i.Repository,
		&i.Tag,
		&i.Digest,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllRepositories = `-- name: ListAllRepositories :many
SELECT
    p.key                    AS project_key,
    p.name                   AS project_name,
    r.key                    AS repo_key,
    m.repository             AS repository,
    COUNT(DISTINCT m.digest) AS manifest_count,
    (SELECT COUNT(*) FROM oci_tags t
       WHERE t.repository_id = m.repository_id AND t.repository = m.repository) AS tag_count,
    CAST(r.mode = 'proxy' AS INTEGER) AS is_proxy,
    MAX(m.created_at)        AS updated_at
FROM oci_manifests m
JOIN repositories r ON r.id = m.repository_id
JOIN projects p ON p.id = r.project_id
GROUP BY m.repository_id, m.repository
ORDER BY p.key ASC, r.key ASC, m.repository ASC
`

type ListAllRepositoriesRow struct {
	ProjectKey    string      `json:"project_key"`
	ProjectName   string      `json:"project_name"`
	RepoKey       string      `json:"repo_key"`
	Repository    string      `json:"repository"`
	ManifestCount int64       `json:"manifest_count"`
	TagCount      int64       `json:"tag_count"`
	IsProxy       int64       `json:"is_proxy"`
	UpdatedAt     interface{} `json:"updated_at"`
}

// Every OCI image across all repositories, joined to its typed repository and
// project, with tag and manifest counts, for the browser's index. is_proxy is 1
// for a proxy repository.
func (q *Queries) ListAllRepositories(ctx context.Context) ([]ListAllRepositoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllRepositoriesRow{}
	for rows.Next() {
		var i ListAllRepositoriesRow
		if err := rows.Scan(
			&i.ProjectKey,
			&i.ProjectName,
			&i.RepoKey,
			&i.Repository,
			&i.ManifestCount,
			&i.TagCount,
			&i.IsProxy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManifestPayloads = `-- name: ListManifestPayloads :many
SELECT payload FROM oci_manifests
`

// Every manifest's raw bytes, for garbage collection to mark the config and
// layer blobs each one references. Blobs are a global CAS, so this spans all
// repositories.
func (q *Queries) ListManifestPayloads(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, listManifestPayloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var payload []byte
		if err := rows.Scan(&payload); err != nil {
			return nil, err
		}
		items = append(items, payload)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManifestSizing = `-- name: ListManifestSizing :many
SELECT
    p.key        AS project_key,
    r.key        AS repo_key,
    m.repository AS repository,
    m.digest     AS digest,
    m.size       AS size,
    m.payload    AS payload
FROM oci_manifests m
JOIN repositories r ON r.id = m.repository_id
JOIN projects p ON p.id = r.project_id
`

type ListManifestSizingRow struct {
	ProjectKey string `json:"project_key"`
	RepoKey    string `json:"repo_key"`
	Repository string `json:"repository"`
	Digest     string `json:"digest"`
	Size       int64  `json:"size"`
	Payload    []byte `json:"payload"`
}

// Every manifest's project, repo, image, digest, stored size, and payload, so
// the browser can compute per-image storage: the sum of the distinct blobs each
// image references. Blobs are a shared CAS, so a layer used by two images is
// counted once per image (logical size), not physically.
func (q *Queries) ListManifestSizing(ctx context.Context) ([]ListManifestSizingRow, error) {
	rows, err := q.db.QueryContext(ctx, listManifestSizing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManifestSizingRow{}
	for rows.Next() {
		var i ListManifestSizingRow
		if err := rows.Scan(
			&i.ProjectKey,
			&i.RepoKey,
			&i.Repository,
			&i.Digest,
			&i.Size,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManifestSizingForProject = `-- name: ListManifestSizingForProject :many
SELECT
    r.key        AS repo_key,
    m.repository AS repository,
    m.digest     AS digest,
    m.size       AS size,
    m.payload    AS payload
FROM oci_manifests m
JOIN repositories r ON r.id = m.repository_id
WHERE r.project_id = ?
`

type ListManifestSizingForProjectRow struct {
	RepoKey    string `json:"repo_key"`
	Repository string `json:"repository"`
	Digest     string `json:"digest"`
	Size       int64  `json:"size"`
	Payload    []byte `json:"payload"`
}

// The same per-image sizing rows as ListManifestSizing, scoped to one project,
// for per-project storage accounting (quota usage).
func (q *Queries) ListManifestSizingForProject(ctx context.Context, projectID string) ([]ListManifestSizingForProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listManifestSizingForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManifestSizingForProjectRow{}
	for rows.Next() {
		var i ListManifestSizingForProjectRow
		if err := rows.Scan(
			&i.RepoKey,
			&i.Repository,
			&i.Digest,
			&i.Size,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferrers = `-- name: ListReferrers :many
SELECT digest, media_type, size, artifact_type, payload
FROM oci_manifests
WHERE repository_id = ? AND repository = ? AND subject = ?
ORDER BY created_at DESC
`

type ListReferrersParams struct {
	RepositoryID string `json:"repository_id"`
	Repository   string `json:"repository"`
	Subject      string `json:"subject"`
}

type ListReferrersRow struct {
	Digest       string `json:"digest"`
	MediaType    string `json:"media_type"`
	Size         int64  `json:"size"`
	ArtifactType string `json:"artifact_type"`
	Payload      []byte `json:"payload"`
}

// Manifests whose subject is the given digest (a subject's signatures, SBOMs,
// and other attestations) for the referrers API. Newest first.
func (q *Queries) ListReferrers(ctx context.Context, arg ListReferrersParams) ([]ListReferrersRow, error) {
	rows, err := q.db.QueryContext(ctx, listReferrers, arg.RepositoryID, arg.Repository, arg.Subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReferrersRow{}
	for rows.Next() {
		var i ListReferrersRow
		if err := rows.Scan(
			&i.Digest,
			&i.MediaType,
			&i.Size,
			&i.ArtifactType,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT tag FROM oci_tags
WHERE repository_id = ? AND repository = ? AND tag > ?
ORDER BY tag ASC
LIMIT ?
`

type ListTagsParams struct {
	RepositoryID string `json:"repository_id"`
	Repository   string `json:"repository"`
	Tag          string `json:"tag"`
	Limit        int64  `json:"limit"`
}

// Keyset pagination on `tag`: the empty string sorts before any tag, so the
// first page and subsequent pages share one query.
func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTags,
		arg.RepositoryID,
		arg.Repository,
		arg.Tag,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForRetention = `-- name: ListTagsForRetention :many
SELECT repository, tag, updated_at FROM oci_tags
WHERE repository_id = ?
ORDER BY repository ASC, updated_at DESC, tag DESC
`

type ListTagsForRetentionRow struct {
	Repository string `json:"repository"`
	Tag        string `json:"tag"`
	UpdatedAt  string `json:"updated_at"`
}

// Every tag in a repository, grouped by image and newest first, so a
// keep-last-N policy can keep the newest tags and delete the rest.
func (q *Queries) ListTagsForRetention(ctx context.Context, repositoryID string) ([]ListTagsForRetentionRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForRetention, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsForRetentionRow{}
	for rows.Next() {
		var i ListTagsForRetentionRow
		if err := rows.Scan(&i.Repository, &i.Tag, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsWithManifest = `-- name: ListTagsWithManifest :many
SELECT
    t.tag        AS tag,
    t.digest     AS digest,
    t.updated_at AS updated_at,
    m.media_type AS media_type,
    m.size       AS size,
    m.payload    AS payload
FROM oci_tags t
JOIN oci_manifests m
  ON m.repository_id = t.repository_id AND m.repository = t.repository AND m.digest = t.digest
WHERE t.repository_id = ? AND t.repository = ?
ORDER BY t.updated_at DESC, t.tag ASC
`

type ListTagsWithManifestParams struct {
	RepositoryID string `json:"repository_id"`
	Repository   string `json:"repository"`
}

type ListTagsWithManifestRow struct {
	Tag       string `json:"tag"`
	Digest    string `json:"digest"`
	UpdatedAt string `json:"updated_at"`
	MediaType string `json:"media_type"`
	Size      int64  `json:"size"`
	Payload   []byte `json:"payload"`
}

// Tags in an image joined to the manifest each points at, so the browser can
// show media type and size without a second round-trip. Newest push first.
func (q *Queries) ListTagsWithManifest(ctx context.Context, arg ListTagsWithManifestParams) ([]ListTagsWithManifestRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsWithManifest, arg.RepositoryID, arg.Repository)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsWithManifestRow{}
	for rows.Next() {
		var i ListTagsWithManifestRow
		if err := rows.Scan(
			&i.Tag,
			&i.Digest,
			&i.UpdatedAt,
			&i.MediaType,
			&i.Size,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUntaggedManifests = `-- name: ListUntaggedManifests :many
SELECT m.repository AS repository, m.digest AS digest FROM oci_manifests m
WHERE m.repository_id = ?
  AND NOT EXISTS (
    SELECT 1 FROM oci_tags t
    WHERE t.repository_id = m.repository_id AND t.repository = m.repository AND t.digest = m.digest
  )
`

type ListUntaggedManifestsRow struct {
	Repository string `json:"repository"`
	Digest     string `json:"digest"`
}

// Manifests in a repository that no tag points at, for the delete-untagged policy.
func (q *Queries) ListUntaggedManifests(ctx context.Context, repositoryID string) ([]ListUntaggedManifestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUntaggedManifests, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUntaggedManifestsRow{}
	for rows.Next() {
		var i ListUntaggedManifestsRow
		if err := rows.Scan(&i.Repository, &i.Digest); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manifestExists = `-- name: ManifestExists :one
SELECT COUNT(*) FROM oci_manifests
WHERE repository_id = ? AND repository = ? AND digest = ?
`

type ManifestExistsParams struct {
	RepositoryID string `json:"repository_id"`
	Repository   string `json:"repository"`
	Digest       string `json:"digest"`
}

func (q *Queries) ManifestExists(ctx context.Context, arg ManifestExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, manifestExists, arg.RepositoryID, arg.Repository, arg.Digest)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertManifest = `-- name: UpsertManifest :exec
INSERT INTO oci_manifests (id, repository_id, repository, digest, media_type, payload, size, subject, artifact_type, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (repository_id, repository, digest) DO NOTHING
`

type UpsertManifestParams struct {
	ID           string `json:"id"`
	RepositoryID string `json:"repository_id"`
	Repository   string `json:"repository"`
	Digest       string `json:"digest"`
	MediaType    string `json:"media_type"`
	Payload      []byte `json:"payload"`
	Size         int64  `json:"size"`
	Subject      string `json:"subject"`
	ArtifactType string `json:"artifact_type"`
	CreatedAt    string `json:"created_at"`
}

// Store a manifest by digest. Re-pushing identical content is a no-op, so an
// image can be tagged repeatedly without duplicating the payload. subject and
// artifact_type are denormalized from the payload for the referrers API.
func (q *Queries) UpsertManifest(ctx context.Context, arg UpsertManifestParams) error {
	_, err := q.db.ExecContext(ctx, upsertManifest,
		arg.ID,
		arg.RepositoryID,
		arg.Repository,
		arg.Digest,
		arg.MediaType,
		arg.Payload,
		arg.Size,
		arg.Subject,
		arg.ArtifactType,
		arg.CreatedAt,
	)
	return err
}

const upsertTag = `-- name: UpsertTag :exec
INSERT INTO oci_tags (repository_id, repository, tag, digest, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (repository_id, repository, tag)
DO UPDATE SET digest = excluded.digest, updated_at = excluded.updated_at
`

type UpsertTagParams struct {
	RepositoryID string `json:"repository_id"`
	Repository   string `json:"repository"`
	Tag          string `json:"tag"`
	Digest       string `json:"digest"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) error {
	_, err := q.db.ExecContext(ctx, upsertTag,
		arg.RepositoryID,
		arg.Repository,
		arg.Tag,
		arg.Digest,
		arg.UpdatedAt,
	)
	return err
}
