// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
)

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, key, name, description, allow_auto_create, quota_bytes, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, "key", name, description, created_at, updated_at, allow_auto_create, quota_bytes, verification_key
`

type CreateProjectParams struct {
	ID              string `json:"id"`
	Key             string `json:"key"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	AllowAutoCreate int64  `json:"allow_auto_create"`
	QuotaBytes      int64  `json:"quota_bytes"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.AllowAutoCreate,
		arg.QuotaBytes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AllowAutoCreate,
		&i.QuotaBytes,
		&i.VerificationKey,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, "key", name, description, created_at, updated_at, allow_auto_create, quota_bytes, verification_key FROM projects WHERE id = ?
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AllowAutoCreate,
		&i.QuotaBytes,
		&i.VerificationKey,
	)
	return i, err
}

const getProjectByKey = `-- name: GetProjectByKey :one
SELECT id, "key", name, description, created_at, updated_at, allow_auto_create, quota_bytes, verification_key FROM projects WHERE key = ?
`

func (q *Queries) GetProjectByKey(ctx context.Context, key string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByKey, key)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AllowAutoCreate,
		&i.QuotaBytes,
		&i.VerificationKey,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, "key", name, description, created_at, updated_at, allow_auto_create, quota_bytes, verification_key FROM projects
WHERE key > ?
ORDER BY key ASC
LIMIT ?
`

type ListProjectsParams struct {
	Key   string `json:"key"`
	Limit int64  `json:"limit"`
}

// Keyset pagination on the unique `key` column. The first page passes the empty
// string, which sorts before any valid key, so a single query serves both the
// first page and subsequent pages.
func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, arg.Key, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AllowAutoCreate,
			&i.QuotaBytes,
			&i.VerificationKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectAutoCreate = `-- name: SetProjectAutoCreate :exec
UPDATE projects SET allow_auto_create = ?, updated_at = ? WHERE key = ?
`

type SetProjectAutoCreateParams struct {
	AllowAutoCreate int64  `json:"allow_auto_create"`
	UpdatedAt       string `json:"updated_at"`
	Key             string `json:"key"`
}

func (q *Queries) SetProjectAutoCreate(ctx context.Context, arg SetProjectAutoCreateParams) error {
	_, err := q.db.ExecContext(ctx, setProjectAutoCreate, arg.AllowAutoCreate, arg.UpdatedAt, arg.Key)
	return err
}

const setProjectQuota = `-- name: SetProjectQuota :exec
UPDATE projects SET quota_bytes = ?, updated_at = ? WHERE key = ?
`

type SetProjectQuotaParams struct {
	QuotaBytes int64  `json:"quota_bytes"`
	UpdatedAt  string `json:"updated_at"`
	Key        string `json:"key"`
}

func (q *Queries) SetProjectQuota(ctx context.Context, arg SetProjectQuotaParams) error {
	_, err := q.db.ExecContext(ctx, setProjectQuota, arg.QuotaBytes, arg.UpdatedAt, arg.Key)
	return err
}

const setProjectVerificationKey = `-- name: SetProjectVerificationKey :exec
UPDATE projects SET verification_key = ?, updated_at = ? WHERE key = ?
`

type SetProjectVerificationKeyParams struct {
	VerificationKey string `json:"verification_key"`
	UpdatedAt       string `json:"updated_at"`
	Key             string `json:"key"`
}

func (q *Queries) SetProjectVerificationKey(ctx context.Context, arg SetProjectVerificationKeyParams) error {
	_, err := q.db.ExecContext(ctx, setProjectVerificationKey, arg.VerificationKey, arg.UpdatedAt, arg.Key)
	return err
}
