// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxies.sql

package db

import (
	"context"
)

const createProxy = `-- name: CreateProxy :exec
INSERT INTO registry_proxies (project_id, upstream_url, username, password, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateProxyParams struct {
	ProjectID   string `json:"project_id"`
	UpstreamUrl string `json:"upstream_url"`
	Username    string `json:"username"`
	Password    string `json:"password"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) CreateProxy(ctx context.Context, arg CreateProxyParams) error {
	_, err := q.db.ExecContext(ctx, createProxy,
		arg.ProjectID,
		arg.UpstreamUrl,
		arg.Username,
		arg.Password,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getProxyByProjectID = `-- name: GetProxyByProjectID :one
SELECT project_id, upstream_url, username, password, created_at, updated_at FROM registry_proxies WHERE project_id = ?
`

func (q *Queries) GetProxyByProjectID(ctx context.Context, projectID string) (RegistryProxy, error) {
	row := q.db.QueryRowContext(ctx, getProxyByProjectID, projectID)
	var i RegistryProxy
	err := row.Scan(
		&i.ProjectID,
		&i.UpstreamUrl,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProxies = `-- name: ListProxies :many
SELECT project_id, upstream_url, username, password, created_at, updated_at FROM registry_proxies
`

func (q *Queries) ListProxies(ctx context.Context) ([]RegistryProxy, error) {
	rows, err := q.db.QueryContext(ctx, listProxies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistryProxy{}
	for rows.Next() {
		var i RegistryProxy
		if err := rows.Scan(
			&i.ProjectID,
			&i.UpstreamUrl,
			&i.Username,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
