// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pypi.sql

package db

import (
	"context"
)

const deletePypiFile = `-- name: DeletePypiFile :execrows
DELETE FROM pypi_files
WHERE package_id = (SELECT id FROM pypi_packages WHERE repository_id = ? AND name = ?)
  AND filename = ?
`

type DeletePypiFileParams struct {
	RepositoryID string `json:"repository_id"`
	Name         string `json:"name"`
	Filename     string `json:"filename"`
}

func (q *Queries) DeletePypiFile(ctx context.Context, arg DeletePypiFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePypiFile, arg.RepositoryID, arg.Name, arg.Filename)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPypiFile = `-- name: GetPypiFile :one
SELECT f.package_id, f.blob_digest, f.size, f.sha256, f.upstream_url
FROM pypi_files f
JOIN pypi_packages p ON p.id = f.package_id
WHERE p.repository_id = ? AND f.filename = ?
`

type GetPypiFileParams struct {
	RepositoryID string `json:"repository_id"`
	Filename     string `json:"filename"`
}

type GetPypiFileRow struct {
	PackageID   string `json:"package_id"`
	BlobDigest  string `json:"blob_digest"`
	Size        int64  `json:"size"`
	Sha256      string `json:"sha256"`
	UpstreamUrl string `json:"upstream_url"`
}

// Resolve a distribution filename to its content for download.
func (q *Queries) GetPypiFile(ctx context.Context, arg GetPypiFileParams) (GetPypiFileRow, error) {
	row := q.db.QueryRowContext(ctx, getPypiFile, arg.RepositoryID, arg.Filename)
	var i GetPypiFileRow
	err := row.Scan(
		&i.PackageID,
		&i.BlobDigest,
		&i.Size,
		&i.Sha256,
		&i.UpstreamUrl,
	)
	return i, err
}

const insertPypiFile = `-- name: InsertPypiFile :exec
INSERT INTO pypi_files (id, package_id, version, filename, blob_digest, size, sha256, requires_python, upstream_url, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (package_id, filename)
DO UPDATE SET
    version = excluded.version,
    size = CASE WHEN excluded.blob_digest != '' THEN excluded.size ELSE pypi_files.size END,
    sha256 = excluded.sha256,
    requires_python = excluded.requires_python,
    upstream_url = excluded.upstream_url,
    blob_digest = CASE WHEN excluded.blob_digest != '' THEN excluded.blob_digest ELSE pypi_files.blob_digest END
`

type InsertPypiFileParams struct {
	ID             string `json:"id"`
	PackageID      string `json:"package_id"`
	Version        string `json:"version"`
	Filename       string `json:"filename"`
	BlobDigest     string `json:"blob_digest"`
	Size           int64  `json:"size"`
	Sha256         string `json:"sha256"`
	RequiresPython string `json:"requires_python"`
	UpstreamUrl    string `json:"upstream_url"`
	CreatedAt      string `json:"created_at"`
}

// Record a distribution file. On conflict (a proxy re-listing the same file, or a
// download filling a cached row) update metadata and the blob only when a real
// new digest is supplied, so a fresh simple-index read never clears a cached blob.
func (q *Queries) InsertPypiFile(ctx context.Context, arg InsertPypiFileParams) error {
	_, err := q.db.ExecContext(ctx, insertPypiFile,
		arg.ID,
		arg.PackageID,
		arg.Version,
		arg.Filename,
		arg.BlobDigest,
		arg.Size,
		arg.Sha256,
		arg.RequiresPython,
		arg.UpstreamUrl,
		arg.CreatedAt,
	)
	return err
}

const listAllPypiPackages = `-- name: ListAllPypiPackages :many
SELECT
    p.key         AS project_key,
    p.name        AS project_name,
    r.key         AS repo_key,
    pkg.name_original AS package_name,
    COUNT(f.id)   AS file_count,
    CAST(COALESCE(SUM(f.size), 0) AS INTEGER) AS size_bytes,
    CAST(r.mode = 'proxy' AS INTEGER) AS is_proxy,
    pkg.updated_at AS updated_at
FROM pypi_packages pkg
JOIN repositories r ON r.id = pkg.repository_id
JOIN projects p ON p.id = r.project_id
LEFT JOIN pypi_files f ON f.package_id = pkg.id
GROUP BY pkg.id
ORDER BY p.key ASC, r.key ASC, pkg.name ASC
`

type ListAllPypiPackagesRow struct {
	ProjectKey  string `json:"project_key"`
	ProjectName string `json:"project_name"`
	RepoKey     string `json:"repo_key"`
	PackageName string `json:"package_name"`
	FileCount   int64  `json:"file_count"`
	SizeBytes   int64  `json:"size_bytes"`
	IsProxy     int64  `json:"is_proxy"`
	UpdatedAt   string `json:"updated_at"`
}

// Every PyPI package across all repositories, with file count, total cached size,
// and a proxy flag, for the browser's project-grouped index.
func (q *Queries) ListAllPypiPackages(ctx context.Context) ([]ListAllPypiPackagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPypiPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPypiPackagesRow{}
	for rows.Next() {
		var i ListAllPypiPackagesRow
		if err := rows.Scan(
			&i.ProjectKey,
			&i.ProjectName,
			&i.RepoKey,
			&i.PackageName,
			&i.FileCount,
			&i.SizeBytes,
			&i.IsProxy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPypiBlobDigests = `-- name: ListPypiBlobDigests :many
SELECT DISTINCT blob_digest FROM pypi_files WHERE blob_digest != ''
`

// Distinct blob digests every cached/uploaded file references, for garbage
// collection to mark them alongside other formats. Empty (uncached) rows are excluded.
func (q *Queries) ListPypiBlobDigests(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPypiBlobDigests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blob_digest string
		if err := rows.Scan(&blob_digest); err != nil {
			return nil, err
		}
		items = append(items, blob_digest)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPypiFiles = `-- name: ListPypiFiles :many
SELECT f.filename, f.version, f.sha256, f.requires_python, f.blob_digest, f.size, f.upstream_url
FROM pypi_files f
JOIN pypi_packages p ON p.id = f.package_id
WHERE p.repository_id = ? AND p.name = ?
ORDER BY f.filename ASC
`

type ListPypiFilesParams struct {
	RepositoryID string `json:"repository_id"`
	Name         string `json:"name"`
}

type ListPypiFilesRow struct {
	Filename       string `json:"filename"`
	Version        string `json:"version"`
	Sha256         string `json:"sha256"`
	RequiresPython string `json:"requires_python"`
	BlobDigest     string `json:"blob_digest"`
	Size           int64  `json:"size"`
	UpstreamUrl    string `json:"upstream_url"`
}

// Every distribution file of a package (by normalized name), for the simple index.
func (q *Queries) ListPypiFiles(ctx context.Context, arg ListPypiFilesParams) ([]ListPypiFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPypiFiles, arg.RepositoryID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPypiFilesRow{}
	for rows.Next() {
		var i ListPypiFilesRow
		if err := rows.Scan(
			&i.Filename,
			&i.Version,
			&i.Sha256,
			&i.RequiresPython,
			&i.BlobDigest,
			&i.Size,
			&i.UpstreamUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPypiFilesForRetention = `-- name: ListPypiFilesForRetention :many
SELECT pkg.name AS name, f.version AS version, f.filename AS filename, f.created_at AS created_at
FROM pypi_files f
JOIN pypi_packages pkg ON pkg.id = f.package_id
WHERE pkg.repository_id = ?
ORDER BY pkg.name ASC, f.created_at DESC
`

type ListPypiFilesForRetentionRow struct {
	Name      string `json:"name"`
	Version   string `json:"version"`
	Filename  string `json:"filename"`
	CreatedAt string `json:"created_at"`
}

// Every file in a repository, grouped by package and newest first, for
// keep-last-N-versions pruning.
func (q *Queries) ListPypiFilesForRetention(ctx context.Context, repositoryID string) ([]ListPypiFilesForRetentionRow, error) {
	rows, err := q.db.QueryContext(ctx, listPypiFilesForRetention, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPypiFilesForRetentionRow{}
	for rows.Next() {
		var i ListPypiFilesForRetentionRow
		if err := rows.Scan(
			&i.Name,
			&i.Version,
			&i.Filename,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPypiPackageNames = `-- name: ListPypiPackageNames :many
SELECT name FROM pypi_packages WHERE repository_id = ? ORDER BY name ASC
`

// Normalized names of every package in a repository, for the root simple index.
func (q *Queries) ListPypiPackageNames(ctx context.Context, repositoryID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPypiPackageNames, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pypiFileExists = `-- name: PypiFileExists :one
SELECT COUNT(*) FROM pypi_files f
JOIN pypi_packages p ON p.id = f.package_id
WHERE p.repository_id = ? AND f.filename = ?
`

type PypiFileExistsParams struct {
	RepositoryID string `json:"repository_id"`
	Filename     string `json:"filename"`
}

// Whether a distribution filename already exists in the repository (uploads are
// immutable: re-uploading a filename is rejected).
func (q *Queries) PypiFileExists(ctx context.Context, arg PypiFileExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, pypiFileExists, arg.RepositoryID, arg.Filename)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const setPypiFileBlob = `-- name: SetPypiFileBlob :exec
UPDATE pypi_files SET blob_digest = ?, size = ?
WHERE package_id = ? AND filename = ?
`

type SetPypiFileBlobParams struct {
	BlobDigest string `json:"blob_digest"`
	Size       int64  `json:"size"`
	PackageID  string `json:"package_id"`
	Filename   string `json:"filename"`
}

// Fill a proxied file's cached blob after downloading it from the upstream.
func (q *Queries) SetPypiFileBlob(ctx context.Context, arg SetPypiFileBlobParams) error {
	_, err := q.db.ExecContext(ctx, setPypiFileBlob,
		arg.BlobDigest,
		arg.Size,
		arg.PackageID,
		arg.Filename,
	)
	return err
}

const upsertPypiPackage = `-- name: UpsertPypiPackage :one
INSERT INTO pypi_packages (id, repository_id, name, name_original, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (repository_id, name)
DO UPDATE SET updated_at = excluded.updated_at, name_original = excluded.name_original
RETURNING id
`

type UpsertPypiPackageParams struct {
	ID           string `json:"id"`
	RepositoryID string `json:"repository_id"`
	Name         string `json:"name"`
	NameOriginal string `json:"name_original"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

// Ensure the package row for (repository, normalized name) exists, returning its
// id. A new file of an existing package just bumps updated_at.
func (q *Queries) UpsertPypiPackage(ctx context.Context, arg UpsertPypiPackageParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertPypiPackage,
		arg.ID,
		arg.RepositoryID,
		arg.Name,
		arg.NameOriginal,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
