// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountProjects(ctx context.Context) (int64, error)
	// Distinct repositories across all projects, for the dashboard summary.
	CountRepositories(ctx context.Context) (int64, error)
	CountTags(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProxy(ctx context.Context, arg CreateProxyParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) (int64, error)
	DeleteExpiredSessions(ctx context.Context, expiresAt string) error
	DeleteManifest(ctx context.Context, arg DeleteManifestParams) (int64, error)
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error
	DeleteTag(ctx context.Context, arg DeleteTagParams) (int64, error)
	DeleteTagsForDigest(ctx context.Context, arg DeleteTagsForDigestParams) error
	GetAPITokenByHash(ctx context.Context, tokenHash string) (GetAPITokenByHashRow, error)
	GetManifest(ctx context.Context, arg GetManifestParams) (OciManifest, error)
	GetProjectByID(ctx context.Context, id string) (Project, error)
	GetProjectByKey(ctx context.Context, key string) (Project, error)
	GetProxyByProjectID(ctx context.Context, projectID string) (RegistryProxy, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	GetTag(ctx context.Context, arg GetTagParams) (OciTag, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) (AuditLog, error)
	ListAPITokensByUser(ctx context.Context, userID string) ([]ApiToken, error)
	// Every repository across all projects, with tag and manifest counts, for the
	// registry browser's project-grouped index. A repository exists once it has at
	// least one manifest.
	ListAllRepositories(ctx context.Context) ([]ListAllRepositoriesRow, error)
	ListAuditByProject(ctx context.Context, arg ListAuditByProjectParams) ([]AuditLog, error)
	// Every manifest's raw bytes, for garbage collection to mark the config and
	// layer blobs each one references. Blobs are a global CAS, so this spans all
	// projects.
	ListManifestPayloads(ctx context.Context) ([][]byte, error)
	// Every manifest's project, repository, digest, stored size, and payload, so the
	// browser can compute per-repository storage: the sum of the distinct blobs each
	// repository references. Blobs are a shared CAS, so a layer used by two
	// repositories is counted once per repository (logical size), not physically.
	ListManifestSizing(ctx context.Context) ([]ListManifestSizingRow, error)
	// Keyset pagination on the unique `key` column. The first page passes the empty
	// string, which sorts before any valid key, so a single query serves both the
	// first page and subsequent pages.
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListProxies(ctx context.Context) ([]RegistryProxy, error)
	// Instance-wide recent mutations for the dashboard feed, joined to the project
	// they touched (project_id is nullable for instance-level events).
	ListRecentActivity(ctx context.Context, limit int64) ([]ListRecentActivityRow, error)
	// Manifests whose subject is the given digest (a subject's signatures, SBOMs,
	// and other attestations) for the referrers API. Newest first.
	ListReferrers(ctx context.Context, arg ListReferrersParams) ([]ListReferrersRow, error)
	// Keyset pagination on `tag`: the empty string sorts before any tag, so the
	// first page and subsequent pages share one query.
	ListTags(ctx context.Context, arg ListTagsParams) ([]string, error)
	// Tags in a repository joined to the manifest each points at, so the browser can
	// show media type and size without a second round-trip. Newest push first.
	ListTagsWithManifest(ctx context.Context, arg ListTagsWithManifestParams) ([]ListTagsWithManifestRow, error)
	ManifestExists(ctx context.Context, arg ManifestExistsParams) (int64, error)
	// Store a manifest by digest. Re-pushing identical content is a no-op, so an
	// image can be tagged repeatedly without duplicating the payload. subject and
	// artifact_type are denormalized from the payload for the referrers API.
	UpsertManifest(ctx context.Context, arg UpsertManifestParams) error
	UpsertTag(ctx context.Context, arg UpsertTagParams) error
}

var _ Querier = (*Queries)(nil)
