// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountProjects(ctx context.Context) (int64, error)
	// Distinct repositories across all projects, for the dashboard summary.
	CountRepositories(ctx context.Context) (int64, error)
	CountTags(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProxy(ctx context.Context, arg CreateProxyParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) (int64, error)
	DeleteExpiredSessions(ctx context.Context, expiresAt string) error
	DeleteGenericFile(ctx context.Context, arg DeleteGenericFileParams) (int64, error)
	DeleteManifest(ctx context.Context, arg DeleteManifestParams) (int64, error)
	DeleteNpmDistTag(ctx context.Context, arg DeleteNpmDistTagParams) (int64, error)
	DeleteNpmVersion(ctx context.Context, arg DeleteNpmVersionParams) (int64, error)
	DeleteNugetVersion(ctx context.Context, arg DeleteNugetVersionParams) (int64, error)
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error
	DeleteTag(ctx context.Context, arg DeleteTagParams) (int64, error)
	DeleteTagsForDigest(ctx context.Context, arg DeleteTagsForDigestParams) error
	GetAPITokenByHash(ctx context.Context, tokenHash string) (GetAPITokenByHashRow, error)
	GetGenericFile(ctx context.Context, arg GetGenericFileParams) (GenericFile, error)
	GetManifest(ctx context.Context, arg GetManifestParams) (OciManifest, error)
	GetNpmPackage(ctx context.Context, arg GetNpmPackageParams) (NpmPackage, error)
	// The blob digest and size for one package version's tarball, to serve it.
	GetNpmTarball(ctx context.Context, arg GetNpmTarballParams) (GetNpmTarballRow, error)
	// The blob digest and size for one version's .nupkg, to serve it.
	GetNugetNupkg(ctx context.Context, arg GetNugetNupkgParams) (GetNugetNupkgRow, error)
	GetNugetPackage(ctx context.Context, arg GetNugetPackageParams) (NugetPackage, error)
	GetProjectByID(ctx context.Context, id string) (Project, error)
	GetProjectByKey(ctx context.Context, key string) (Project, error)
	GetProxyByProjectID(ctx context.Context, projectID string) (RegistryProxy, error)
	GetRetentionPolicy(ctx context.Context, projectID string) (RetentionPolicy, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	GetTag(ctx context.Context, arg GetTagParams) (OciTag, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) (AuditLog, error)
	// Store a published version. First-writer-wins: a duplicate (already rejected at
	// the handler) is a no-op rather than a transaction error.
	InsertNpmVersion(ctx context.Context, arg InsertNpmVersionParams) error
	InsertNugetVersion(ctx context.Context, arg InsertNugetVersionParams) error
	ListAPITokensByUser(ctx context.Context, userID string) ([]ApiToken, error)
	// Every generic file across all projects, with a proxy flag, for the registry
	// browser's generic index. is_proxy is 1 when the file's project is a mirror.
	ListAllGenericFiles(ctx context.Context) ([]ListAllGenericFilesRow, error)
	// Every npm package across all projects, with version count, total tarball size,
	// and a proxy flag, for the registry browser's package index. is_proxy is 1 when
	// the package's project is a pull-through mirror.
	ListAllNpmPackages(ctx context.Context) ([]ListAllNpmPackagesRow, error)
	// Every NuGet package across all projects, with version count, total nupkg size,
	// and a proxy flag, for the registry browser's package index.
	ListAllNugetPackages(ctx context.Context) ([]ListAllNugetPackagesRow, error)
	// Every repository across all projects, with tag and manifest counts, for the
	// registry browser's project-grouped index. A repository exists once it has at
	// least one manifest. is_proxy is 1 when the repository's project is a
	// pull-through mirror (a registry_proxies row exists), so the browser can label
	// it Local vs Proxy without a second query.
	ListAllRepositories(ctx context.Context) ([]ListAllRepositoriesRow, error)
	ListAuditByProject(ctx context.Context, arg ListAuditByProjectParams) ([]AuditLog, error)
	// Distinct blob digests every generic file references, for garbage collection to
	// mark them alongside OCI manifests and npm tarballs (shared CAS across formats).
	ListGenericBlobDigests(ctx context.Context) ([]string, error)
	// Every manifest's raw bytes, for garbage collection to mark the config and
	// layer blobs each one references. Blobs are a global CAS, so this spans all
	// projects.
	ListManifestPayloads(ctx context.Context) ([][]byte, error)
	// Every manifest's project, repository, digest, stored size, and payload, so the
	// browser can compute per-repository storage: the sum of the distinct blobs each
	// repository references. Blobs are a shared CAS, so a layer used by two
	// repositories is counted once per repository (logical size), not physically.
	ListManifestSizing(ctx context.Context) ([]ListManifestSizingRow, error)
	ListNpmDistTags(ctx context.Context, arg ListNpmDistTagsParams) ([]ListNpmDistTagsRow, error)
	// Distinct tarball digests every npm version references, for garbage collection
	// to mark them alongside OCI blobs. Blobs are a shared CAS spanning all formats.
	ListNpmTarballDigests(ctx context.Context) ([]string, error)
	// Every published version of a package, oldest first, with the verbatim version
	// metadata and its tarball's digests, so the packument can be rebuilt.
	ListNpmVersions(ctx context.Context, arg ListNpmVersionsParams) ([]ListNpmVersionsRow, error)
	// Every version in a project, grouped by package and newest first, for
	// keep-last-N pruning.
	ListNpmVersionsForRetention(ctx context.Context, projectID string) ([]ListNpmVersionsForRetentionRow, error)
	// Distinct nupkg digests every version references, for garbage collection to
	// mark them alongside the other formats (shared CAS).
	ListNugetBlobDigests(ctx context.Context) ([]string, error)
	// Every version of a package, oldest first, with the nuspec and nupkg pointer,
	// for the flat-container index, registration, and downloads.
	ListNugetVersions(ctx context.Context, arg ListNugetVersionsParams) ([]ListNugetVersionsRow, error)
	// Every version in a project, grouped by package and newest first, for
	// keep-last-N pruning.
	ListNugetVersionsForRetention(ctx context.Context, projectID string) ([]ListNugetVersionsForRetentionRow, error)
	// Keyset pagination on the unique `key` column. The first page passes the empty
	// string, which sorts before any valid key, so a single query serves both the
	// first page and subsequent pages.
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListProxies(ctx context.Context) ([]RegistryProxy, error)
	// Instance-wide recent mutations for the dashboard feed, joined to the project
	// they touched (project_id is nullable for instance-level events).
	ListRecentActivity(ctx context.Context, limit int64) ([]ListRecentActivityRow, error)
	// Manifests whose subject is the given digest (a subject's signatures, SBOMs,
	// and other attestations) for the referrers API. Newest first.
	ListReferrers(ctx context.Context, arg ListReferrersParams) ([]ListReferrersRow, error)
	// Every project with an effective policy (keeps some, or sweeps untagged), with
	// its key, for a retention run.
	ListRetentionPolicies(ctx context.Context) ([]ListRetentionPoliciesRow, error)
	// Keyset pagination on `tag`: the empty string sorts before any tag, so the
	// first page and subsequent pages share one query.
	ListTags(ctx context.Context, arg ListTagsParams) ([]string, error)
	// Every tag in a project, grouped by repository and newest first, so a
	// keep-last-N policy can keep the newest tags and delete the rest.
	ListTagsForRetention(ctx context.Context, projectID string) ([]ListTagsForRetentionRow, error)
	// Tags in a repository joined to the manifest each points at, so the browser can
	// show media type and size without a second round-trip. Newest push first.
	ListTagsWithManifest(ctx context.Context, arg ListTagsWithManifestParams) ([]ListTagsWithManifestRow, error)
	// Manifests in a project that no tag points at, for the delete-untagged policy.
	ListUntaggedManifests(ctx context.Context, projectID string) ([]ListUntaggedManifestsRow, error)
	ManifestExists(ctx context.Context, arg ManifestExistsParams) (int64, error)
	// Whether a specific version is already published. npm forbids overwriting a
	// published version, so the handler rejects a re-publish before inserting.
	NpmVersionExists(ctx context.Context, arg NpmVersionExistsParams) (int64, error)
	// Whether a specific version is already pushed. NuGet forbids overwriting a
	// published version, so the handler rejects a re-push before inserting.
	NugetVersionExists(ctx context.Context, arg NugetVersionExistsParams) (int64, error)
	// Packages in a project whose id contains the (lowercased) query, newest first,
	// for the search resource. An empty query matches all.
	SearchNugetPackages(ctx context.Context, arg SearchNugetPackagesParams) ([]SearchNugetPackagesRow, error)
	// Store a file at a path, replacing any existing file there (generic paths are
	// mutable: a re-upload overwrites).
	UpsertGenericFile(ctx context.Context, arg UpsertGenericFileParams) error
	// Store a manifest by digest. Re-pushing identical content is a no-op, so an
	// image can be tagged repeatedly without duplicating the payload. subject and
	// artifact_type are denormalized from the payload for the referrers API.
	UpsertManifest(ctx context.Context, arg UpsertManifestParams) error
	UpsertNpmDistTag(ctx context.Context, arg UpsertNpmDistTagParams) error
	// Ensure the package row for (project, name) exists, returning its id.
	// Publishing a new version of an existing package just bumps updated_at.
	UpsertNpmPackage(ctx context.Context, arg UpsertNpmPackageParams) (string, error)
	// Ensure the package row for (project, id_lower) exists, returning its id.
	// Pushing a new version of an existing package bumps updated_at.
	UpsertNugetPackage(ctx context.Context, arg UpsertNugetPackageParams) (string, error)
	UpsertRetentionPolicy(ctx context.Context, arg UpsertRetentionPolicyParams) error
	UpsertTag(ctx context.Context, arg UpsertTagParams) error
}

var _ Querier = (*Queries)(nil)
