// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repositories.sql

package db

import (
	"context"
)

const addVirtualMember = `-- name: AddVirtualMember :exec
INSERT INTO virtual_repo_members (virtual_repo_id, member_repo_id, position)
VALUES (?, ?, ?)
`

type AddVirtualMemberParams struct {
	VirtualRepoID string `json:"virtual_repo_id"`
	MemberRepoID  string `json:"member_repo_id"`
	Position      int64  `json:"position"`
}

func (q *Queries) AddVirtualMember(ctx context.Context, arg AddVirtualMemberParams) error {
	_, err := q.db.ExecContext(ctx, addVirtualMember, arg.VirtualRepoID, arg.MemberRepoID, arg.Position)
	return err
}

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (
    id, project_id, key, name, format, mode,
    upstream_url, upstream_username, upstream_password,
    keep_last, delete_untagged, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, "key", name, format, mode, upstream_url, upstream_username, upstream_password, keep_last, delete_untagged, created_at, updated_at
`

type CreateRepositoryParams struct {
	ID               string `json:"id"`
	ProjectID        string `json:"project_id"`
	Key              string `json:"key"`
	Name             string `json:"name"`
	Format           string `json:"format"`
	Mode             string `json:"mode"`
	UpstreamUrl      string `json:"upstream_url"`
	UpstreamUsername string `json:"upstream_username"`
	UpstreamPassword string `json:"upstream_password"`
	KeepLast         int64  `json:"keep_last"`
	DeleteUntagged   int64  `json:"delete_untagged"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRowContext(ctx, createRepository,
		arg.ID,
		arg.ProjectID,
		arg.Key,
		arg.Name,
		arg.Format,
		arg.Mode,
		arg.UpstreamUrl,
		arg.UpstreamUsername,
		arg.UpstreamPassword,
		arg.KeepLast,
		arg.DeleteUntagged,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Format,
		&i.Mode,
		&i.UpstreamUrl,
		&i.UpstreamUsername,
		&i.UpstreamPassword,
		&i.KeepLast,
		&i.DeleteUntagged,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRepository = `-- name: DeleteRepository :execrows
DELETE FROM repositories
WHERE project_id = ? AND key = ?
`

type DeleteRepositoryParams struct {
	ProjectID string `json:"project_id"`
	Key       string `json:"key"`
}

func (q *Queries) DeleteRepository(ctx context.Context, arg DeleteRepositoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRepository, arg.ProjectID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteVirtualMembers = `-- name: DeleteVirtualMembers :exec
DELETE FROM virtual_repo_members WHERE virtual_repo_id = ?
`

func (q *Queries) DeleteVirtualMembers(ctx context.Context, virtualRepoID string) error {
	_, err := q.db.ExecContext(ctx, deleteVirtualMembers, virtualRepoID)
	return err
}

const getRepository = `-- name: GetRepository :one
SELECT id, project_id, "key", name, format, mode, upstream_url, upstream_username, upstream_password, keep_last, delete_untagged, created_at, updated_at FROM repositories
WHERE project_id = ? AND key = ?
`

type GetRepositoryParams struct {
	ProjectID string `json:"project_id"`
	Key       string `json:"key"`
}

func (q *Queries) GetRepository(ctx context.Context, arg GetRepositoryParams) (Repository, error) {
	row := q.db.QueryRowContext(ctx, getRepository, arg.ProjectID, arg.Key)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Format,
		&i.Mode,
		&i.UpstreamUrl,
		&i.UpstreamUsername,
		&i.UpstreamPassword,
		&i.KeepLast,
		&i.DeleteUntagged,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryByID = `-- name: GetRepositoryByID :one
SELECT id, project_id, "key", name, format, mode, upstream_url, upstream_username, upstream_password, keep_last, delete_untagged, created_at, updated_at FROM repositories WHERE id = ?
`

func (q *Queries) GetRepositoryByID(ctx context.Context, id string) (Repository, error) {
	row := q.db.QueryRowContext(ctx, getRepositoryByID, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Format,
		&i.Mode,
		&i.UpstreamUrl,
		&i.UpstreamUsername,
		&i.UpstreamPassword,
		&i.KeepLast,
		&i.DeleteUntagged,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllRepositoryRows = `-- name: ListAllRepositoryRows :many
SELECT r.id, r.project_id, r."key", r.name, r.format, r.mode, r.upstream_url, r.upstream_username, r.upstream_password, r.keep_last, r.delete_untagged, r.created_at, r.updated_at, p.key AS project_key, p.name AS project_name
FROM repositories r
JOIN projects p ON p.id = r.project_id
ORDER BY p.key ASC, r.key ASC
`

type ListAllRepositoryRowsRow struct {
	ID               string `json:"id"`
	ProjectID        string `json:"project_id"`
	Key              string `json:"key"`
	Name             string `json:"name"`
	Format           string `json:"format"`
	Mode             string `json:"mode"`
	UpstreamUrl      string `json:"upstream_url"`
	UpstreamUsername string `json:"upstream_username"`
	UpstreamPassword string `json:"upstream_password"`
	KeepLast         int64  `json:"keep_last"`
	DeleteUntagged   int64  `json:"delete_untagged"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
	ProjectKey       string `json:"project_key"`
	ProjectName      string `json:"project_name"`
}

// Every repository across all projects, with its project key, for the browser
// and instance-wide operations (retention, listing).
func (q *Queries) ListAllRepositoryRows(ctx context.Context) ([]ListAllRepositoryRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllRepositoryRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllRepositoryRowsRow{}
	for rows.Next() {
		var i ListAllRepositoryRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Name,
			&i.Format,
			&i.Mode,
			&i.UpstreamUrl,
			&i.UpstreamUsername,
			&i.UpstreamPassword,
			&i.KeepLast,
			&i.DeleteUntagged,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoriesByProject = `-- name: ListRepositoriesByProject :many
SELECT id, project_id, "key", name, format, mode, upstream_url, upstream_username, upstream_password, keep_last, delete_untagged, created_at, updated_at FROM repositories
WHERE project_id = ?
ORDER BY key ASC
`

func (q *Queries) ListRepositoriesByProject(ctx context.Context, projectID string) ([]Repository, error) {
	rows, err := q.db.QueryContext(ctx, listRepositoriesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Name,
			&i.Format,
			&i.Mode,
			&i.UpstreamUrl,
			&i.UpstreamUsername,
			&i.UpstreamPassword,
			&i.KeepLast,
			&i.DeleteUntagged,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoriesWithPolicy = `-- name: ListRepositoriesWithPolicy :many
SELECT id, project_id, "key", name, format, mode, upstream_url, upstream_username, upstream_password, keep_last, delete_untagged, created_at, updated_at FROM repositories
WHERE keep_last > 0 OR delete_untagged = 1
`

// Repositories that have an effective retention policy, for a retention run.
func (q *Queries) ListRepositoriesWithPolicy(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.QueryContext(ctx, listRepositoriesWithPolicy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Name,
			&i.Format,
			&i.Mode,
			&i.UpstreamUrl,
			&i.UpstreamUsername,
			&i.UpstreamPassword,
			&i.KeepLast,
			&i.DeleteUntagged,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVirtualMembers = `-- name: ListVirtualMembers :many
SELECT r.id, r.project_id, r."key", r.name, r.format, r.mode, r.upstream_url, r.upstream_username, r.upstream_password, r.keep_last, r.delete_untagged, r.created_at, r.updated_at FROM virtual_repo_members m
JOIN repositories r ON r.id = m.member_repo_id
WHERE m.virtual_repo_id = ?
ORDER BY m.position ASC
`

// Member repositories of a virtual repository, in configured order.
func (q *Queries) ListVirtualMembers(ctx context.Context, virtualRepoID string) ([]Repository, error) {
	rows, err := q.db.QueryContext(ctx, listVirtualMembers, virtualRepoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Name,
			&i.Format,
			&i.Mode,
			&i.UpstreamUrl,
			&i.UpstreamUsername,
			&i.UpstreamPassword,
			&i.KeepLast,
			&i.DeleteUntagged,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepository = `-- name: UpdateRepository :one
UPDATE repositories
SET name = ?, upstream_url = ?, upstream_username = ?, upstream_password = ?,
    keep_last = ?, delete_untagged = ?, updated_at = ?
WHERE id = ?
RETURNING id, project_id, "key", name, format, mode, upstream_url, upstream_username, upstream_password, keep_last, delete_untagged, created_at, updated_at
`

type UpdateRepositoryParams struct {
	Name             string `json:"name"`
	UpstreamUrl      string `json:"upstream_url"`
	UpstreamUsername string `json:"upstream_username"`
	UpstreamPassword string `json:"upstream_password"`
	KeepLast         int64  `json:"keep_last"`
	DeleteUntagged   int64  `json:"delete_untagged"`
	UpdatedAt        string `json:"updated_at"`
	ID               string `json:"id"`
}

func (q *Queries) UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) (Repository, error) {
	row := q.db.QueryRowContext(ctx, updateRepository,
		arg.Name,
		arg.UpstreamUrl,
		arg.UpstreamUsername,
		arg.UpstreamPassword,
		arg.KeepLast,
		arg.DeleteUntagged,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Format,
		&i.Mode,
		&i.UpstreamUrl,
		&i.UpstreamUsername,
		&i.UpstreamPassword,
		&i.KeepLast,
		&i.DeleteUntagged,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
