// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package db

import (
	"context"
)

const getRetentionPolicy = `-- name: GetRetentionPolicy :one
SELECT project_id, keep_last, delete_untagged, updated_at FROM retention_policies WHERE project_id = ?
`

func (q *Queries) GetRetentionPolicy(ctx context.Context, projectID string) (RetentionPolicy, error) {
	row := q.db.QueryRowContext(ctx, getRetentionPolicy, projectID)
	var i RetentionPolicy
	err := row.Scan(
		&i.ProjectID,
		&i.KeepLast,
		&i.DeleteUntagged,
		&i.UpdatedAt,
	)
	return i, err
}

const listRetentionPolicies = `-- name: ListRetentionPolicies :many
SELECT rp.project_id, rp.keep_last, rp.delete_untagged, p.key AS project_key
FROM retention_policies rp
JOIN projects p ON p.id = rp.project_id
WHERE rp.keep_last > 0 OR rp.delete_untagged = 1
`

type ListRetentionPoliciesRow struct {
	ProjectID      string `json:"project_id"`
	KeepLast       int64  `json:"keep_last"`
	DeleteUntagged int64  `json:"delete_untagged"`
	ProjectKey     string `json:"project_key"`
}

// Every project with an effective policy (keeps some, or sweeps untagged), with
// its key, for a retention run.
func (q *Queries) ListRetentionPolicies(ctx context.Context) ([]ListRetentionPoliciesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRetentionPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRetentionPoliciesRow{}
	for rows.Next() {
		var i ListRetentionPoliciesRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.KeepLast,
			&i.DeleteUntagged,
			&i.ProjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRetentionPolicy = `-- name: UpsertRetentionPolicy :exec
INSERT INTO retention_policies (project_id, keep_last, delete_untagged, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (project_id)
DO UPDATE SET keep_last = excluded.keep_last, delete_untagged = excluded.delete_untagged, updated_at = excluded.updated_at
`

type UpsertRetentionPolicyParams struct {
	ProjectID      string `json:"project_id"`
	KeepLast       int64  `json:"keep_last"`
	DeleteUntagged int64  `json:"delete_untagged"`
	UpdatedAt      string `json:"updated_at"`
}

func (q *Queries) UpsertRetentionPolicy(ctx context.Context, arg UpsertRetentionPolicyParams) error {
	_, err := q.db.ExecContext(ctx, upsertRetentionPolicy,
		arg.ProjectID,
		arg.KeepLast,
		arg.DeleteUntagged,
		arg.UpdatedAt,
	)
	return err
}
