// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rubygems.sql

package db

import (
	"context"
)

const deleteGemVersion = `-- name: DeleteGemVersion :execrows
DELETE FROM gem_versions
WHERE gem_id = (SELECT id FROM gem_gems WHERE repository_id = ? AND name = ?)
  AND full_name = ?
`

type DeleteGemVersionParams struct {
	RepositoryID string `json:"repository_id"`
	Name         string `json:"name"`
	FullName     string `json:"full_name"`
}

func (q *Queries) DeleteGemVersion(ctx context.Context, arg DeleteGemVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGemVersion, arg.RepositoryID, arg.Name, arg.FullName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const gemVersionExists = `-- name: GemVersionExists :one
SELECT COUNT(*) FROM gem_versions v
JOIN gem_gems g ON g.id = v.gem_id
WHERE g.repository_id = ? AND g.name = ? AND v.full_name = ?
`

type GemVersionExistsParams struct {
	RepositoryID string `json:"repository_id"`
	Name         string `json:"name"`
	FullName     string `json:"full_name"`
}

func (q *Queries) GemVersionExists(ctx context.Context, arg GemVersionExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, gemVersionExists, arg.RepositoryID, arg.Name, arg.FullName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGemFile = `-- name: GetGemFile :one
SELECT v.gem_id, v.blob_digest, v.size, v.sha256, v.upstream_url
FROM gem_versions v
JOIN gem_gems g ON g.id = v.gem_id
WHERE g.repository_id = ? AND v.full_name = ?
`

type GetGemFileParams struct {
	RepositoryID string `json:"repository_id"`
	FullName     string `json:"full_name"`
}

type GetGemFileRow struct {
	GemID       string `json:"gem_id"`
	BlobDigest  string `json:"blob_digest"`
	Size        int64  `json:"size"`
	Sha256      string `json:"sha256"`
	UpstreamUrl string `json:"upstream_url"`
}

// Resolve a .gem by its full name (name-number) for download.
func (q *Queries) GetGemFile(ctx context.Context, arg GetGemFileParams) (GetGemFileRow, error) {
	row := q.db.QueryRowContext(ctx, getGemFile, arg.RepositoryID, arg.FullName)
	var i GetGemFileRow
	err := row.Scan(
		&i.GemID,
		&i.BlobDigest,
		&i.Size,
		&i.Sha256,
		&i.UpstreamUrl,
	)
	return i, err
}

const insertGemVersion = `-- name: InsertGemVersion :exec
INSERT INTO gem_versions (id, gem_id, version, platform, number, full_name, info_deps, info_reqs, sha256, blob_digest, size, yanked, upstream_url, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (gem_id, full_name)
DO UPDATE SET
    version      = excluded.version,
    platform     = excluded.platform,
    number       = excluded.number,
    info_deps    = excluded.info_deps,
    info_reqs    = excluded.info_reqs,
    sha256       = excluded.sha256,
    size         = CASE WHEN excluded.blob_digest != '' THEN excluded.size ELSE gem_versions.size END,
    yanked       = excluded.yanked,
    upstream_url = excluded.upstream_url,
    blob_digest  = CASE WHEN excluded.blob_digest != '' THEN excluded.blob_digest ELSE gem_versions.blob_digest END
`

type InsertGemVersionParams struct {
	ID          string `json:"id"`
	GemID       string `json:"gem_id"`
	Version     string `json:"version"`
	Platform    string `json:"platform"`
	Number      string `json:"number"`
	FullName    string `json:"full_name"`
	InfoDeps    string `json:"info_deps"`
	InfoReqs    string `json:"info_reqs"`
	Sha256      string `json:"sha256"`
	BlobDigest  string `json:"blob_digest"`
	Size        int64  `json:"size"`
	Yanked      int64  `json:"yanked"`
	UpstreamUrl string `json:"upstream_url"`
	CreatedAt   string `json:"created_at"`
}

// Record a gem version. On conflict (a proxy re-listing, or a download filling a
// cached row) update metadata and only overwrite the blob when a real digest is
// supplied, so a fresh index read never clears a cached blob.
func (q *Queries) InsertGemVersion(ctx context.Context, arg InsertGemVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertGemVersion,
		arg.ID,
		arg.GemID,
		arg.Version,
		arg.Platform,
		arg.Number,
		arg.FullName,
		arg.InfoDeps,
		arg.InfoReqs,
		arg.Sha256,
		arg.BlobDigest,
		arg.Size,
		arg.Yanked,
		arg.UpstreamUrl,
		arg.CreatedAt,
	)
	return err
}

const listAllGems = `-- name: ListAllGems :many
SELECT
    p.key         AS project_key,
    p.name        AS project_name,
    r.key         AS repo_key,
    g.name        AS gem_name,
    COUNT(v.id)   AS version_count,
    CAST(COALESCE(SUM(v.size), 0) AS INTEGER) AS size_bytes,
    CAST(r.mode = 'proxy' AS INTEGER) AS is_proxy,
    g.updated_at  AS updated_at
FROM gem_gems g
JOIN repositories r ON r.id = g.repository_id
JOIN projects p ON p.id = r.project_id
LEFT JOIN gem_versions v ON v.gem_id = g.id
GROUP BY g.id
ORDER BY p.key ASC, r.key ASC, g.name ASC
`

type ListAllGemsRow struct {
	ProjectKey   string `json:"project_key"`
	ProjectName  string `json:"project_name"`
	RepoKey      string `json:"repo_key"`
	GemName      string `json:"gem_name"`
	VersionCount int64  `json:"version_count"`
	SizeBytes    int64  `json:"size_bytes"`
	IsProxy      int64  `json:"is_proxy"`
	UpdatedAt    string `json:"updated_at"`
}

// Every gem across all repositories, with version count, total cached size, and a
// proxy flag, for the browser's project-grouped index.
func (q *Queries) ListAllGems(ctx context.Context) ([]ListAllGemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllGems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllGemsRow{}
	for rows.Next() {
		var i ListAllGemsRow
		if err := rows.Scan(
			&i.ProjectKey,
			&i.ProjectName,
			&i.RepoKey,
			&i.GemName,
			&i.VersionCount,
			&i.SizeBytes,
			&i.IsProxy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGemBlobDigests = `-- name: ListGemBlobDigests :many
SELECT DISTINCT blob_digest FROM gem_versions WHERE blob_digest != ''
`

func (q *Queries) ListGemBlobDigests(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listGemBlobDigests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blob_digest string
		if err := rows.Scan(&blob_digest); err != nil {
			return nil, err
		}
		items = append(items, blob_digest)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGemInfoVersions = `-- name: ListGemInfoVersions :many
SELECT v.number, v.info_deps, v.info_reqs, v.yanked
FROM gem_versions v
JOIN gem_gems g ON g.id = v.gem_id
WHERE g.repository_id = ? AND g.name = ?
ORDER BY v.created_at ASC
`

type ListGemInfoVersionsParams struct {
	RepositoryID string `json:"repository_id"`
	Name         string `json:"name"`
}

type ListGemInfoVersionsRow struct {
	Number   string `json:"number"`
	InfoDeps string `json:"info_deps"`
	InfoReqs string `json:"info_reqs"`
	Yanked   int64  `json:"yanked"`
}

// Every version of a gem (by name) for the /info/<gem> file, oldest first.
func (q *Queries) ListGemInfoVersions(ctx context.Context, arg ListGemInfoVersionsParams) ([]ListGemInfoVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGemInfoVersions, arg.RepositoryID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGemInfoVersionsRow{}
	for rows.Next() {
		var i ListGemInfoVersionsRow
		if err := rows.Scan(
			&i.Number,
			&i.InfoDeps,
			&i.InfoReqs,
			&i.Yanked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGemNames = `-- name: ListGemNames :many
SELECT name FROM gem_gems WHERE repository_id = ? ORDER BY name ASC
`

func (q *Queries) ListGemNames(ctx context.Context, repositoryID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listGemNames, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGemVersionsForGem = `-- name: ListGemVersionsForGem :many
SELECT v.number, v.version, v.platform, v.size, v.yanked, v.sha256
FROM gem_versions v
JOIN gem_gems g ON g.id = v.gem_id
WHERE g.repository_id = ? AND g.name = ?
ORDER BY v.created_at DESC
`

type ListGemVersionsForGemParams struct {
	RepositoryID string `json:"repository_id"`
	Name         string `json:"name"`
}

type ListGemVersionsForGemRow struct {
	Number   string `json:"number"`
	Version  string `json:"version"`
	Platform string `json:"platform"`
	Size     int64  `json:"size"`
	Yanked   int64  `json:"yanked"`
	Sha256   string `json:"sha256"`
}

// Every version of a gem for its detail page.
func (q *Queries) ListGemVersionsForGem(ctx context.Context, arg ListGemVersionsForGemParams) ([]ListGemVersionsForGemRow, error) {
	rows, err := q.db.QueryContext(ctx, listGemVersionsForGem, arg.RepositoryID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGemVersionsForGemRow{}
	for rows.Next() {
		var i ListGemVersionsForGemRow
		if err := rows.Scan(
			&i.Number,
			&i.Version,
			&i.Platform,
			&i.Size,
			&i.Yanked,
			&i.Sha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGemVersionsForIndex = `-- name: ListGemVersionsForIndex :many
SELECT g.name AS name, v.number AS number, v.info_deps AS info_deps, v.info_reqs AS info_reqs
FROM gem_versions v
JOIN gem_gems g ON g.id = v.gem_id
WHERE g.repository_id = ? AND v.yanked = 0
ORDER BY g.name ASC, v.created_at ASC
`

type ListGemVersionsForIndexRow struct {
	Name     string `json:"name"`
	Number   string `json:"number"`
	InfoDeps string `json:"info_deps"`
	InfoReqs string `json:"info_reqs"`
}

// Every non-yanked version across all gems in a repository, for the /versions
// compact-index file. Grouped by gem name.
func (q *Queries) ListGemVersionsForIndex(ctx context.Context, repositoryID string) ([]ListGemVersionsForIndexRow, error) {
	rows, err := q.db.QueryContext(ctx, listGemVersionsForIndex, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGemVersionsForIndexRow{}
	for rows.Next() {
		var i ListGemVersionsForIndexRow
		if err := rows.Scan(
			&i.Name,
			&i.Number,
			&i.InfoDeps,
			&i.InfoReqs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGemVersionsForRetention = `-- name: ListGemVersionsForRetention :many
SELECT g.name AS name, v.number AS number, v.full_name AS full_name, v.created_at AS created_at
FROM gem_versions v
JOIN gem_gems g ON g.id = v.gem_id
WHERE g.repository_id = ?
ORDER BY g.name ASC, v.created_at DESC
`

type ListGemVersionsForRetentionRow struct {
	Name      string `json:"name"`
	Number    string `json:"number"`
	FullName  string `json:"full_name"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) ListGemVersionsForRetention(ctx context.Context, repositoryID string) ([]ListGemVersionsForRetentionRow, error) {
	rows, err := q.db.QueryContext(ctx, listGemVersionsForRetention, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGemVersionsForRetentionRow{}
	for rows.Next() {
		var i ListGemVersionsForRetentionRow
		if err := rows.Scan(
			&i.Name,
			&i.Number,
			&i.FullName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGemVersionBlob = `-- name: SetGemVersionBlob :exec
UPDATE gem_versions SET blob_digest = ?, size = ?
WHERE full_name = ? AND gem_id IN (SELECT id FROM gem_gems WHERE repository_id = ?)
`

type SetGemVersionBlobParams struct {
	BlobDigest   string `json:"blob_digest"`
	Size         int64  `json:"size"`
	FullName     string `json:"full_name"`
	RepositoryID string `json:"repository_id"`
}

// Fill a proxied version's cached blob after download. full_name is unique within
// a repository (name is unique per repo, and full_name is name-number), so the
// repository plus full_name identify the row without the gem name.
func (q *Queries) SetGemVersionBlob(ctx context.Context, arg SetGemVersionBlobParams) error {
	_, err := q.db.ExecContext(ctx, setGemVersionBlob,
		arg.BlobDigest,
		arg.Size,
		arg.FullName,
		arg.RepositoryID,
	)
	return err
}

const setGemYanked = `-- name: SetGemYanked :execrows
UPDATE gem_versions SET yanked = ?
WHERE gem_id = (SELECT id FROM gem_gems WHERE repository_id = ? AND name = ?)
  AND number = ?
`

type SetGemYankedParams struct {
	Yanked       int64  `json:"yanked"`
	RepositoryID string `json:"repository_id"`
	Name         string `json:"name"`
	Number       string `json:"number"`
}

func (q *Queries) SetGemYanked(ctx context.Context, arg SetGemYankedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setGemYanked,
		arg.Yanked,
		arg.RepositoryID,
		arg.Name,
		arg.Number,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertGem = `-- name: UpsertGem :one
INSERT INTO gem_gems (id, repository_id, name, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (repository_id, name)
DO UPDATE SET updated_at = excluded.updated_at
RETURNING id
`

type UpsertGemParams struct {
	ID           string `json:"id"`
	RepositoryID string `json:"repository_id"`
	Name         string `json:"name"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

// Ensure the gem row for (repository, name) exists, returning its id.
func (q *Queries) UpsertGem(ctx context.Context, arg UpsertGemParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertGem,
		arg.ID,
		arg.RepositoryID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
