// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan.sql

package db

import (
	"context"
)

const createFinding = `-- name: CreateFinding :exec
INSERT INTO scan_findings (
    id, scan_id, project_id, vuln_id, package, version,
    ecosystem, severity, severity_rank, summary, fixed_version, reference_url
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateFindingParams struct {
	ID           string `json:"id"`
	ScanID       string `json:"scan_id"`
	ProjectID    string `json:"project_id"`
	VulnID       string `json:"vuln_id"`
	Package      string `json:"package"`
	Version      string `json:"version"`
	Ecosystem    string `json:"ecosystem"`
	Severity     string `json:"severity"`
	SeverityRank int64  `json:"severity_rank"`
	Summary      string `json:"summary"`
	FixedVersion string `json:"fixed_version"`
	ReferenceUrl string `json:"reference_url"`
}

func (q *Queries) CreateFinding(ctx context.Context, arg CreateFindingParams) error {
	_, err := q.db.ExecContext(ctx, createFinding,
		arg.ID,
		arg.ScanID,
		arg.ProjectID,
		arg.VulnID,
		arg.Package,
		arg.Version,
		arg.Ecosystem,
		arg.Severity,
		arg.SeverityRank,
		arg.Summary,
		arg.FixedVersion,
		arg.ReferenceUrl,
	)
	return err
}

const createScan = `-- name: CreateScan :one
INSERT INTO scans (
    id, project_id, repo_id, image, digest, source_digest,
    component_count, critical, high, medium, low, unknown, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, repo_id, image, digest, source_digest, component_count, critical, high, medium, low, unknown, created_at
`

type CreateScanParams struct {
	ID             string `json:"id"`
	ProjectID      string `json:"project_id"`
	RepoID         string `json:"repo_id"`
	Image          string `json:"image"`
	Digest         string `json:"digest"`
	SourceDigest   string `json:"source_digest"`
	ComponentCount int64  `json:"component_count"`
	Critical       int64  `json:"critical"`
	High           int64  `json:"high"`
	Medium         int64  `json:"medium"`
	Low            int64  `json:"low"`
	Unknown        int64  `json:"unknown"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) CreateScan(ctx context.Context, arg CreateScanParams) (Scan, error) {
	row := q.db.QueryRowContext(ctx, createScan,
		arg.ID,
		arg.ProjectID,
		arg.RepoID,
		arg.Image,
		arg.Digest,
		arg.SourceDigest,
		arg.ComponentCount,
		arg.Critical,
		arg.High,
		arg.Medium,
		arg.Low,
		arg.Unknown,
		arg.CreatedAt,
	)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RepoID,
		&i.Image,
		&i.Digest,
		&i.SourceDigest,
		&i.ComponentCount,
		&i.Critical,
		&i.High,
		&i.Medium,
		&i.Low,
		&i.Unknown,
		&i.CreatedAt,
	)
	return i, err
}

const deleteScansForArtifact = `-- name: DeleteScansForArtifact :exec
DELETE FROM scans WHERE repo_id = ? AND image = ? AND digest = ?
`

type DeleteScansForArtifactParams struct {
	RepoID string `json:"repo_id"`
	Image  string `json:"image"`
	Digest string `json:"digest"`
}

// Remove any prior scan of this artifact so a rescan replaces it (findings
// cascade). Keeps at most one scan per (repo_id, image, digest).
func (q *Queries) DeleteScansForArtifact(ctx context.Context, arg DeleteScansForArtifactParams) error {
	_, err := q.db.ExecContext(ctx, deleteScansForArtifact, arg.RepoID, arg.Image, arg.Digest)
	return err
}

const getLatestScan = `-- name: GetLatestScan :one
SELECT id, project_id, repo_id, image, digest, source_digest, component_count, critical, high, medium, low, unknown, created_at FROM scans
WHERE repo_id = ? AND image = ? AND digest = ?
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestScanParams struct {
	RepoID string `json:"repo_id"`
	Image  string `json:"image"`
	Digest string `json:"digest"`
}

// The most recent scan of an artifact (there is normally one; ORDER BY guards
// against a race leaving two).
func (q *Queries) GetLatestScan(ctx context.Context, arg GetLatestScanParams) (Scan, error) {
	row := q.db.QueryRowContext(ctx, getLatestScan, arg.RepoID, arg.Image, arg.Digest)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RepoID,
		&i.Image,
		&i.Digest,
		&i.SourceDigest,
		&i.ComponentCount,
		&i.Critical,
		&i.High,
		&i.Medium,
		&i.Low,
		&i.Unknown,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifactsByVuln = `-- name: ListArtifactsByVuln :many
SELECT p.key AS project_key, p.name AS project_name, r.key AS repo_key,
       s.image, s.digest, f.package, f.version, f.severity, f.severity_rank,
       f.fixed_version, s.created_at
FROM scan_findings f
JOIN scans s ON s.id = f.scan_id
JOIN repositories r ON r.id = s.repo_id
JOIN projects p ON p.id = s.project_id
WHERE f.vuln_id = ?
ORDER BY s.created_at DESC, s.image ASC
`

type ListArtifactsByVulnRow struct {
	ProjectKey   string `json:"project_key"`
	ProjectName  string `json:"project_name"`
	RepoKey      string `json:"repo_key"`
	Image        string `json:"image"`
	Digest       string `json:"digest"`
	Package      string `json:"package"`
	Version      string `json:"version"`
	Severity     string `json:"severity"`
	SeverityRank int64  `json:"severity_rank"`
	FixedVersion string `json:"fixed_version"`
	CreatedAt    string `json:"created_at"`
}

// The artifacts affected by one vulnerability: the "CVE -> artifacts" query. Joins
// through scans to the repository and project for human-readable keys.
func (q *Queries) ListArtifactsByVuln(ctx context.Context, vulnID string) ([]ListArtifactsByVulnRow, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsByVuln, vulnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactsByVulnRow{}
	for rows.Next() {
		var i ListArtifactsByVulnRow
		if err := rows.Scan(
			&i.ProjectKey,
			&i.ProjectName,
			&i.RepoKey,
			&i.Image,
			&i.Digest,
			&i.Package,
			&i.Version,
			&i.Severity,
			&i.SeverityRank,
			&i.FixedVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsForScan = `-- name: ListFindingsForScan :many
SELECT id, scan_id, project_id, vuln_id, package, version, ecosystem, severity, severity_rank, summary, fixed_version, reference_url FROM scan_findings
WHERE scan_id = ?
ORDER BY severity_rank DESC, vuln_id ASC, package ASC
`

func (q *Queries) ListFindingsForScan(ctx context.Context, scanID string) ([]ScanFinding, error) {
	rows, err := q.db.QueryContext(ctx, listFindingsForScan, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanFinding{}
	for rows.Next() {
		var i ScanFinding
		if err := rows.Scan(
			&i.ID,
			&i.ScanID,
			&i.ProjectID,
			&i.VulnID,
			&i.Package,
			&i.Version,
			&i.Ecosystem,
			&i.Severity,
			&i.SeverityRank,
			&i.Summary,
			&i.FixedVersion,
			&i.ReferenceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVulnerabilities = `-- name: ListVulnerabilities :many
SELECT vuln_id, severity, severity_rank, summary,
       COUNT(DISTINCT scan_id) AS artifact_count
FROM scan_findings
GROUP BY vuln_id, severity, severity_rank, summary
ORDER BY severity_rank DESC, artifact_count DESC, vuln_id ASC
`

type ListVulnerabilitiesRow struct {
	VulnID        string `json:"vuln_id"`
	Severity      string `json:"severity"`
	SeverityRank  int64  `json:"severity_rank"`
	Summary       string `json:"summary"`
	ArtifactCount int64  `json:"artifact_count"`
}

// One row per distinct vulnerability across all stored scans, with the number of
// affected artifacts. severity and summary are properties of the vulnerability so
// they are constant within a vuln_id; grouping by them yields one row per vuln.
func (q *Queries) ListVulnerabilities(ctx context.Context) ([]ListVulnerabilitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listVulnerabilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVulnerabilitiesRow{}
	for rows.Next() {
		var i ListVulnerabilitiesRow
		if err := rows.Scan(
			&i.VulnID,
			&i.Severity,
			&i.SeverityRank,
			&i.Summary,
			&i.ArtifactCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
