// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, token_hash, user_id, created_at, expires_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, token_hash, user_id, created_at, expires_at
`

type CreateSessionParams struct {
	ID        string `json:"id"`
	TokenHash string `json:"token_hash"`
	UserID    string `json:"user_id"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT sessions.id, sessions.token_hash, sessions.user_id, sessions.created_at, sessions.expires_at, users.id, users.username, users.email, users.password_hash, users.is_admin, users.created_at, users.updated_at
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = ?
`

type GetSessionByTokenHashRow struct {
	Session Session `json:"session"`
	User    User    `json:"user"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.TokenHash,
		&i.Session.UserID,
		&i.Session.CreatedAt,
		&i.Session.ExpiresAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.IsAdmin,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}
