// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: terraform.sql

package db

import (
	"context"
)

const deleteTerraformVersion = `-- name: DeleteTerraformVersion :execrows
DELETE FROM terraform_versions
WHERE module_id = (SELECT id FROM terraform_modules WHERE repository_id = ? AND name = ? AND provider = ?)
  AND version = ?
`

type DeleteTerraformVersionParams struct {
	RepositoryID string `json:"repository_id"`
	Name         string `json:"name"`
	Provider     string `json:"provider"`
	Version      string `json:"version"`
}

func (q *Queries) DeleteTerraformVersion(ctx context.Context, arg DeleteTerraformVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTerraformVersion,
		arg.RepositoryID,
		arg.Name,
		arg.Provider,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTerraformVersion = `-- name: GetTerraformVersion :one
SELECT blob_digest, size FROM terraform_versions
WHERE module_id = ? AND version = ?
`

type GetTerraformVersionParams struct {
	ModuleID string `json:"module_id"`
	Version  string `json:"version"`
}

type GetTerraformVersionRow struct {
	BlobDigest string `json:"blob_digest"`
	Size       int64  `json:"size"`
}

// Resolve a module version to its archive blob for download.
func (q *Queries) GetTerraformVersion(ctx context.Context, arg GetTerraformVersionParams) (GetTerraformVersionRow, error) {
	row := q.db.QueryRowContext(ctx, getTerraformVersion, arg.ModuleID, arg.Version)
	var i GetTerraformVersionRow
	err := row.Scan(&i.BlobDigest, &i.Size)
	return i, err
}

const insertTerraformVersion = `-- name: InsertTerraformVersion :exec
INSERT INTO terraform_versions (id, module_id, version, blob_digest, size, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertTerraformVersionParams struct {
	ID         string `json:"id"`
	ModuleID   string `json:"module_id"`
	Version    string `json:"version"`
	BlobDigest string `json:"blob_digest"`
	Size       int64  `json:"size"`
	CreatedAt  string `json:"created_at"`
}

func (q *Queries) InsertTerraformVersion(ctx context.Context, arg InsertTerraformVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertTerraformVersion,
		arg.ID,
		arg.ModuleID,
		arg.Version,
		arg.BlobDigest,
		arg.Size,
		arg.CreatedAt,
	)
	return err
}

const listAllTerraformModules = `-- name: ListAllTerraformModules :many
SELECT
    p.key         AS project_key,
    p.name        AS project_name,
    r.key         AS repo_key,
    m.name        AS module_name,
    m.provider    AS provider,
    COUNT(v.id)   AS version_count,
    CAST(COALESCE(SUM(v.size), 0) AS INTEGER) AS size_bytes,
    CAST(r.mode = 'proxy' AS INTEGER) AS is_proxy,
    m.updated_at  AS updated_at
FROM terraform_modules m
JOIN repositories r ON r.id = m.repository_id
JOIN projects p ON p.id = r.project_id
LEFT JOIN terraform_versions v ON v.module_id = m.id
GROUP BY m.id
ORDER BY p.key ASC, r.key ASC, m.name ASC, m.provider ASC
`

type ListAllTerraformModulesRow struct {
	ProjectKey   string `json:"project_key"`
	ProjectName  string `json:"project_name"`
	RepoKey      string `json:"repo_key"`
	ModuleName   string `json:"module_name"`
	Provider     string `json:"provider"`
	VersionCount int64  `json:"version_count"`
	SizeBytes    int64  `json:"size_bytes"`
	IsProxy      int64  `json:"is_proxy"`
	UpdatedAt    string `json:"updated_at"`
}

// Every Terraform module across all repositories, with version count, total size,
// and a proxy flag (always local), for the browser's project-grouped index.
func (q *Queries) ListAllTerraformModules(ctx context.Context) ([]ListAllTerraformModulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllTerraformModules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTerraformModulesRow{}
	for rows.Next() {
		var i ListAllTerraformModulesRow
		if err := rows.Scan(
			&i.ProjectKey,
			&i.ProjectName,
			&i.RepoKey,
			&i.ModuleName,
			&i.Provider,
			&i.VersionCount,
			&i.SizeBytes,
			&i.IsProxy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTerraformBlobDigests = `-- name: ListTerraformBlobDigests :many
SELECT DISTINCT blob_digest FROM terraform_versions WHERE blob_digest != ''
`

func (q *Queries) ListTerraformBlobDigests(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTerraformBlobDigests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blob_digest string
		if err := rows.Scan(&blob_digest); err != nil {
			return nil, err
		}
		items = append(items, blob_digest)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTerraformVersions = `-- name: ListTerraformVersions :many
SELECT version FROM terraform_versions
WHERE module_id = ?
ORDER BY created_at DESC
`

// Every version of a module, newest first, for the /versions endpoint.
func (q *Queries) ListTerraformVersions(ctx context.Context, moduleID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTerraformVersions, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var version string
		if err := rows.Scan(&version); err != nil {
			return nil, err
		}
		items = append(items, version)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTerraformVersionsForModule = `-- name: ListTerraformVersionsForModule :many
SELECT v.version, v.size
FROM terraform_versions v
JOIN terraform_modules m ON m.id = v.module_id
WHERE m.repository_id = ? AND m.name = ? AND m.provider = ?
ORDER BY v.created_at DESC
`

type ListTerraformVersionsForModuleParams struct {
	RepositoryID string `json:"repository_id"`
	Name         string `json:"name"`
	Provider     string `json:"provider"`
}

type ListTerraformVersionsForModuleRow struct {
	Version string `json:"version"`
	Size    int64  `json:"size"`
}

// Every version of a module for its detail page.
func (q *Queries) ListTerraformVersionsForModule(ctx context.Context, arg ListTerraformVersionsForModuleParams) ([]ListTerraformVersionsForModuleRow, error) {
	rows, err := q.db.QueryContext(ctx, listTerraformVersionsForModule, arg.RepositoryID, arg.Name, arg.Provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTerraformVersionsForModuleRow{}
	for rows.Next() {
		var i ListTerraformVersionsForModuleRow
		if err := rows.Scan(&i.Version, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTerraformVersionsForRetention = `-- name: ListTerraformVersionsForRetention :many
SELECT m.name AS name, m.provider AS provider, v.version AS version, v.created_at AS created_at
FROM terraform_versions v
JOIN terraform_modules m ON m.id = v.module_id
WHERE m.repository_id = ?
ORDER BY m.name ASC, m.provider ASC, v.created_at DESC
`

type ListTerraformVersionsForRetentionRow struct {
	Name      string `json:"name"`
	Provider  string `json:"provider"`
	Version   string `json:"version"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) ListTerraformVersionsForRetention(ctx context.Context, repositoryID string) ([]ListTerraformVersionsForRetentionRow, error) {
	rows, err := q.db.QueryContext(ctx, listTerraformVersionsForRetention, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTerraformVersionsForRetentionRow{}
	for rows.Next() {
		var i ListTerraformVersionsForRetentionRow
		if err := rows.Scan(
			&i.Name,
			&i.Provider,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveTerraformModule = `-- name: ResolveTerraformModule :one
SELECT m.id AS module_id, m.repository_id AS repository_id
FROM terraform_modules m
JOIN repositories r ON r.id = m.repository_id
WHERE r.project_id = ? AND r.format = 'terraform' AND m.name = ? AND m.provider = ?
ORDER BY m.updated_at DESC
LIMIT 1
`

type ResolveTerraformModuleParams struct {
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
	Provider  string `json:"provider"`
}

type ResolveTerraformModuleRow struct {
	ModuleID     string `json:"module_id"`
	RepositoryID string `json:"repository_id"`
}

// Resolve (project, name, provider) to a module and its repository, for the
// registry read protocol (the namespace in a module address is the project key).
func (q *Queries) ResolveTerraformModule(ctx context.Context, arg ResolveTerraformModuleParams) (ResolveTerraformModuleRow, error) {
	row := q.db.QueryRowContext(ctx, resolveTerraformModule, arg.ProjectID, arg.Name, arg.Provider)
	var i ResolveTerraformModuleRow
	err := row.Scan(&i.ModuleID, &i.RepositoryID)
	return i, err
}

const terraformVersionExists = `-- name: TerraformVersionExists :one
SELECT COUNT(*) FROM terraform_versions v
JOIN terraform_modules m ON m.id = v.module_id
WHERE m.repository_id = ? AND m.name = ? AND m.provider = ? AND v.version = ?
`

type TerraformVersionExistsParams struct {
	RepositoryID string `json:"repository_id"`
	Name         string `json:"name"`
	Provider     string `json:"provider"`
	Version      string `json:"version"`
}

func (q *Queries) TerraformVersionExists(ctx context.Context, arg TerraformVersionExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, terraformVersionExists,
		arg.RepositoryID,
		arg.Name,
		arg.Provider,
		arg.Version,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertTerraformModule = `-- name: UpsertTerraformModule :one
INSERT INTO terraform_modules (id, repository_id, name, provider, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (repository_id, name, provider)
DO UPDATE SET updated_at = excluded.updated_at
RETURNING id
`

type UpsertTerraformModuleParams struct {
	ID           string `json:"id"`
	RepositoryID string `json:"repository_id"`
	Name         string `json:"name"`
	Provider     string `json:"provider"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

// Ensure the module row for (repository, name, provider) exists, returning its id.
func (q *Queries) UpsertTerraformModule(ctx context.Context, arg UpsertTerraformModuleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertTerraformModule,
		arg.ID,
		arg.RepositoryID,
		arg.Name,
		arg.Provider,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
