// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package db

import (
	"context"
	"database/sql"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (id, project_id, url, secret, events, active, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 1, ?, ?)
RETURNING id, project_id, url, secret, events, active, created_at, updated_at
`

type CreateWebhookParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	Url       string `json:"url"`
	Secret    string `json:"secret"`
	Events    string `json:"events"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, createWebhook,
		arg.ID,
		arg.ProjectID,
		arg.Url,
		arg.Secret,
		arg.Events,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :execrows
DELETE FROM webhooks WHERE id = ? AND project_id = ?
`

type DeleteWebhookParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWebhook, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, project_id, url, secret, events, active, created_at, updated_at FROM webhooks WHERE id = ? AND project_id = ?
`

type GetWebhookParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetWebhook(ctx context.Context, arg GetWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhook, arg.ID, arg.ProjectID)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookCursor = `-- name: GetWebhookCursor :one
SELECT last_created_at, last_id FROM webhook_cursor WHERE id = 1
`

type GetWebhookCursorRow struct {
	LastCreatedAt string `json:"last_created_at"`
	LastID        string `json:"last_id"`
}

func (q *Queries) GetWebhookCursor(ctx context.Context) (GetWebhookCursorRow, error) {
	row := q.db.QueryRowContext(ctx, getWebhookCursor)
	var i GetWebhookCursorRow
	err := row.Scan(&i.LastCreatedAt, &i.LastID)
	return i, err
}

const listActiveWebhooksForProject = `-- name: ListActiveWebhooksForProject :many
SELECT id, url, secret, events FROM webhooks WHERE project_id = ? AND active = 1
`

type ListActiveWebhooksForProjectRow struct {
	ID     string `json:"id"`
	Url    string `json:"url"`
	Secret string `json:"secret"`
	Events string `json:"events"`
}

// Active webhooks for a project, for the dispatcher to match against an event.
func (q *Queries) ListActiveWebhooksForProject(ctx context.Context, projectID string) ([]ListActiveWebhooksForProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveWebhooksForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveWebhooksForProjectRow{}
	for rows.Next() {
		var i ListActiveWebhooksForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Secret,
			&i.Events,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditSince = `-- name: ListAuditSince :many
SELECT a.id, a.project_id, p.key AS project_key, a.actor, a.action, a.target_type, a.target_id, a.metadata, a.created_at
FROM audit_log a
JOIN projects p ON p.id = a.project_id
WHERE a.project_id IS NOT NULL
  AND (a.created_at > ?1
       OR (a.created_at = ?1 AND a.id > ?2))
ORDER BY a.created_at ASC, a.id ASC
LIMIT ?3
`

type ListAuditSinceParams struct {
	CursorCreatedAt string `json:"cursor_created_at"`
	CursorID        string `json:"cursor_id"`
	RowLimit        int64  `json:"row_limit"`
}

type ListAuditSinceRow struct {
	ID         string         `json:"id"`
	ProjectID  sql.NullString `json:"project_id"`
	ProjectKey string         `json:"project_key"`
	Actor      string         `json:"actor"`
	Action     string         `json:"action"`
	TargetType string         `json:"target_type"`
	TargetID   string         `json:"target_id"`
	Metadata   string         `json:"metadata"`
	CreatedAt  string         `json:"created_at"`
}

// Audit entries after the dispatcher's cursor, oldest first, with the project key
// for the delivery payload. Keyset on (created_at, id): created_at is RFC3339Nano
// (fixed width, so it orders lexically) and id breaks ties.
func (q *Queries) ListAuditSince(ctx context.Context, arg ListAuditSinceParams) ([]ListAuditSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditSince, arg.CursorCreatedAt, arg.CursorID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditSinceRow{}
	for rows.Next() {
		var i ListAuditSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectKey,
			&i.Actor,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByProject = `-- name: ListWebhooksByProject :many
SELECT id, project_id, url, secret, events, active, created_at, updated_at FROM webhooks WHERE project_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListWebhooksByProject(ctx context.Context, projectID string) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxAuditCursor = `-- name: MaxAuditCursor :one
SELECT created_at, id FROM audit_log ORDER BY created_at DESC, id DESC LIMIT 1
`

type MaxAuditCursorRow struct {
	CreatedAt string `json:"created_at"`
	ID        string `json:"id"`
}

// The newest audit entry, to seed the dispatcher cursor on first run.
func (q *Queries) MaxAuditCursor(ctx context.Context) (MaxAuditCursorRow, error) {
	row := q.db.QueryRowContext(ctx, maxAuditCursor)
	var i MaxAuditCursorRow
	err := row.Scan(&i.CreatedAt, &i.ID)
	return i, err
}

const setWebhookCursor = `-- name: SetWebhookCursor :exec
UPDATE webhook_cursor SET last_created_at = ?, last_id = ? WHERE id = 1
`

type SetWebhookCursorParams struct {
	LastCreatedAt string `json:"last_created_at"`
	LastID        string `json:"last_id"`
}

func (q *Queries) SetWebhookCursor(ctx context.Context, arg SetWebhookCursorParams) error {
	_, err := q.db.ExecContext(ctx, setWebhookCursor, arg.LastCreatedAt, arg.LastID)
	return err
}
